export const SHELL_LABELS = {
  ja: {
    academyCode: '塾コード',
    academyName: '塾名',
    account: 'アカウント',
    adminMenu: '管理者メニュー',
    back: '戻る',
    academyMembers: '会員管理',
    allChecks: '全ヘルスチェック実行',
    allChecksHint: 'ローカル、Docker、クラウドの順で確認します。',
    cloud: 'クラウドサーバー',
    devClientLog: 'クライアントログ出力',
    devClientLogHint:
      'このクライアントから標準の console.log を 1 件出力します。',
    devServerLog: 'サーバーログ出力',
    devServerLogHint:
      '開発サーバーで最小コストのログを 1 件出力します。',
    devHealth: '開発/状態確認',
    devShowStudentSkinPreview: 'スキンプレビューを表示',
    devShowStudentSkinPreviewHint: 'スチューデントスキンのシリアライズデータを確認します。',
    devUnmountLoginContainer: 'ログインコンテナをアンマウント',
    devUnmountLoginContainerHint:
      'ログイントグルで非表示時に login コンテナをツリーから外します。',
    devUnmountProfileContainer: 'プロフィールコンテナをアンマウント',
    devUnmountProfileContainerHint:
      'プロフィールトグルで非表示時に profile コンテナをツリーから外します。',
    devLicenseCreate: 'ライセンス生成',
    devLicenseCreateHint: '未割り当てライセンスを 1 件発行します。',
    devResult: '開発者アクション結果',
    devTableInit: 'テーブル初期化',
    devTableInitHint:
      '管理対象テーブルを再作成し、マイグレーションを順に適用します。',
    devTableInitAndSeed: 'テーブル初期化とテストデータ注入',
    devTableInitAndSeedHint:
      'テーブルを初期化したあと、Test Academy のテストデータをまとめて投入します。',
    dark: 'ダーク',
    docker: 'Dockerサーバー',
    env: '環境',
    classroom: '授業',
    general: '一般設定',
    confirmPassword: 'パスワード確認',
    createAccount: 'アカウント作成',
    copyLicenseCode: 'ライセンスコードをコピー',
    debugLog: 'デバッグログ',
    displayName: '表示名',
    email: 'メール',
    edit: '編集',
    guestHint:
      '登録したアカウントでログインするとプロフィールと保護コントロールを確認できます。',
    invalid: 'アカウントIDまたはパスワードが正しくありません。',
    accountInactive: 'このアカウントは無効です。',
    accountOnHold: 'このアカウントは現在保留中です。',
    accountPending: 'このアカウントは承認待ちです。',
    academyInactive: '所属塾は現在利用できません。',
    academyCreateFailed:
      '塾を作成できませんでした。しばらくしてからもう一度お試しください。',
    duplicateLoginId:
      'このログインIDは既に使用されています。別のIDを入力してください。',
    language: '言語',
    lastChecked: '最終確認',
    light: 'ライト',
    local: 'ローカルサーバー',
    locked: '保護設定は現在ロックされています。',
    loginNotice: 'ログイン案内',
    login: 'ログイン',
    loginId: 'ログインID',
    loginIdPlaceholder: 'ログインID',
    members: 'メンバー',
    myInfo: 'マイ情報',
    pendingApproval: '加入承認',
    preset: 'プリセット管理',
    memberRegisterBody:
      'Member アカウントを申請すると、root または admin の承認後に利用できます。',
    memberRegisterSuccess:
      'Member 登録申請を送信しました。承認後にログインできます。',
    memberRole: '希望権限',
    memberRoleAdmin: 'Admin',
    memberRoleStudent: 'Student',
    memberRoleTeacher: 'Teacher',
    memberRoleInvalid: '有効な権限を選択してください。',
    noAccount:
      'まだ作成されたアカウントがありません。先に登録を完了してください。',
    note: 'メモ',
    presetPlaceholderBody: 'プリセットエディターのプレースホルダーです。詳細な編集機能は後で追加されます。',
    presetPlaceholderTitle: 'プリセット',
    presetTitle: 'プリセット一覧',
    presetNew: '+ 新規プリセット',
    presetName: 'プリセット名',
    presetSave: 'プリセットを保存',
    presetDelete: 'プリセット削除',
    presetDeleteConfirm: 'このプリセットを削除しますか？',
    presetShowDetails: '詳しく見る',
    presetHideDetails: '要約で見る',
    presetSummary: '要約',
    presetNoItems: '品目がありません。',
    presetCategoryAll: '全部',
    presetSearch: '検索',
    presetSearchPlaceholder: 'アイテム名またはSKUで検索',
    presetManualItemNamePlaceholder: 'アイテム名を入力',
    presetManualAdd: 'アイテム追加',
    presetManualCategoryRequired: 'カテゴリーを選択',
    presetItemName: 'アイテム名',
    presetSku: 'SKU',
    presetLch: 'L / C / H',
    presetCategoryBaseFoundation: 'ベース・ファンデーション',
    presetCategoryBlush: 'チーク',
    presetCategoryLipColor: 'リップカラー',
    presetCategoryEyeshadow: 'アイシャドウ',
    presetCategoryContour: 'コントゥア',
    presetCategoryHighlighter: 'ハイライター',
    presetCategoryEtc: 'その他',
    profileEdit: 'プロフィール編集',
    profileEditBody: '必要な項目を変更して保存できます。',
    profilePasswordPlaceholder: '空欄のままなら変更しません。',
    profileSave: 'プロフィール保存',
    profileSaveSuccess: 'プロフィールを更新しました。',
    profileUpdateFailed:
      'プロフィールを更新できませんでした。しばらくしてからもう一度お試しください。',
    profileStatusDenied: 'このアカウント状態は変更できません。',
    profileStatusInvalid: '有効な状態を選択してください。',
    profileAuthPolicyDenied: 'Auth Policy は root のみ変更できます。',
    status: '状態',
    studentOptions: '学生情報',
    studentOptionsPlaceholderBody:
      '肌データ、スキン特性メモ、好みポイントをここで確認して編集できます。',
    studentOptionsPlaceholderTitle: '肌と好み',
    studentOptionsSkinData: 'スキンデータ',
    studentOptionsMySkin: 'マイスキン',
    studentOptionsTraits: 'スキン特性',
    studentOptionsPreferencePoints: '好みポイント',
    studentOptionsCategory: 'カテゴリー',
    studentOptionsActions: 'アクション',
    studentOptionsLightness: '明度 (L)',
    studentOptionsHue: '色相 (H)',
    studentOptionsChroma: '彩度 (C)',
    studentOptionsRangeRadius: '範囲半径',
    studentOptionsSave: 'スキンを保存',
    studentOptionsReset: 'リセット',
    studentOptionsDone: '完了',
    studentOptionsToolSelect: 'ポイント選択',
    studentOptionsToolRange: '範囲設定',
    studentOptionsZoom: 'ズーム',
    studentOptionsTraitsPlaceholder: 'アンダートーン、感受性、仕上がりなどのメモを入力してください。',
    studentOptionsNoTraits: 'スキン特性のメモがまだありません。',
    studentOptionsNoPoints: '好みポイントが設定されていません。',
    studentOptionsPoints: 'ポイント',
    studentOptionsDeleteTitle: 'ポイント削除',
    studentOptionsDeleteMessage: 'ポイント {n} を削除しますか？',
    studentOptionsDeleteConfirm: '削除',
    studentOptionsUseFullSkinRange: '平面を全範囲で使う',
    statusActive: 'ACTIVE',
    statusHold: 'HOLD',
    statusInactive: 'INACTIVE',
    availableSchedulePlaceholderBody:
      '予約可能スケジュールエディターのプレースホルダーです。詳細な編集機能は後で追加されます。',
    availableSchedulePlaceholderTitle: '予約可能スケジュール',
    password: 'パスワード',
    passwordPlaceholder: 'パスワード',
    passwordSetupFailed:
      'パスワードを準備できませんでした。しばらくしてからもう一度お試しください。',
    phone: '携帯番号',
    profile: 'プロフィール',
    profileAcademy: '所属塾',
    profileBody: '現在サインインしているアカウント情報です。',
    profileCodeAdmin: 'Admin Code',
    profileCodeStudent: 'Student Code',
    profileCodeTeacher: 'Teacher Code',
    profileId: 'サインイン中ID',
    profilePassword: 'マスクされたパスワード',
    profileRole: '権限',
    protectedControls: '保護コントロール',
    protectedLocked: 'サインインするまでロックされています。',
    protectedSignin: '保護設定にサインイン',
    protectedUnlocked: '現在のアカウントで保護設定を利用できます。',
    registerRoot: 'Root 登録',
    registerRootBody:
      'ライセンス、塾情報、root アカウント情報をまとめて登録します。',
    registerType: '登録タイプ',
    registerTypeUser: 'Member',
    registerTypeRoot: 'Root',
    inventory: 'インベントリ',
    inventoryList: 'インベントリ管理',
    inventoryAdd: '品目追加',
    inventoryItemName: '品目名',
    inventorySku: 'SKU',
    inventoryBarcode: 'バーコード',
    inventoryCost: '原価',
    inventoryPrice: '販売価格',
    inventoryColorL: 'L値',
    inventoryColorC: 'C値',
    inventoryColorH: 'H値',
    inventoryStock: '在庫数',
    inventoryReorderLevel: '発注基準数',
    inventoryCategory: 'カテゴリー',
    inventorySupplier: '仕入先',
    inventoryLocation: '保管場所',
    inventoryImageUrl: '画像URL',
    inventoryNote: 'メモ',
    inventoryStatusActive: '有効',
    inventoryStatusInactive: '無効',
    inventoryCategoryEtc: 'その他',
    inventoryNoItems: '在庫品目がまだありません。',
    inventoryAddTitle: '品目を追加',
    inventoryEdit: '編集',
    inventoryDelete: '削除',
    inventoryDeleteConfirmTitle: '品目削除',
    inventoryDeleteConfirmMessage: '{name} を削除しますか？',
    inventoryDeleteConfirm: '削除',
    inventorySave: '保存',
    reservation: '授業予約',
    reservationPlaceholderBody:
      '予約のプレースホルダーです。予約フローは後で追加されます。',
    reservationPlaceholderTitle: '予約',
    reservationView: '予約承認',
    reservationViewPlaceholderBody:
      '予約確認のプレースホルダーです。講師の予約一覧は後で追加されます。',
    reservationViewPlaceholderTitle: '予約確認',
    reservationTeacher: '担当の先生',
    reservationSelectDate: '日付を選ぶ',
    reservationTimeSlots: '時間帯',
    reservationConfirm: '予約確認',
    reservationDate: '日付',
    reservationTime: '時間',
    reservationBookLesson: 'レッスンを予約する',
    reservationBooked: '予約完了',
    reservationBookedBody: '予約申請が送信されました。確認後に承認されます。',
    reservationMyList: 'マイ予約',
    reservationNone: '予約はまだありません。',
    reservationSlotTaken: '取得済み',
    reservationSlotBooked: '予約済み',
    reservationStatusConfirmed: '確定',
    reservationStatusPending: '承認待ち',
    reservationStatusCanceled: 'キャンセル',
    reservationDetails: '詳細',
    reservationHideDetails: '詳細を閉じる',
    reservationPreset: 'プリセット',
    reservationNote: 'メモ',
    reservationCosmetics: '使用化粧品',
    reservationNoCosmetics: 'この予約に連結された化粧品がありません。',
    reservationViewApprove: '承認',
    reservationViewEmpty: '対応が必要な予約はまだありません。',
    reservationViewMismatchGuide:
      '学生の好み範囲を外れた項目は赤で表示されますが、承認は可能です。',
    reservationViewNoPreference: 'このカテゴリーの学生好みデータがありません。',
    reservationViewPass: '受講券',
    reservationViewPreferenceRanges: '好み範囲',
    reservationViewPresetItems: 'プリセット項目確認',
    reservationViewPending: '承認待ち予約',
    reservationViewCanceled: 'キャンセル済み予約',
    reservationViewReject: '却下',
    reservationViewSkin: '肌',
    reservationViewStudent: '学生',
    reservationViewTrait: '特性',
    reservationViewUpcoming: '確定予約',
    register: '登録',
    registerBody: '登録タイプを選んで必要な情報を入力します。',
    registerSuccess: 'Root アカウントを作成しました。',
    registrationBusy:
      '現在登録を完了できません。しばらくしてからもう一度お試しください。',
    save: '保存',
    result: '結果',
    rootLoginId: 'root ログインID',
    seedPasswordHint: 'シードパスワード規則',
    rootAlreadyExists: 'この塾にはすでに root アカウントがあります。',
    settings: '設定',
    availableSchedule: '授業可能時間',
    availableScheduleGuide: '週次グリッドを塗りつぶして予約可能時間を設定し、特定日の例外は下の例外セクションで管理してください。',
    availableScheduleTimezone: 'スケジュールタイムゾーン',
    availableScheduleWeeklyGrid: '週次グリッド',
    availableScheduleSlotsSelected: '{n} スロット選択中',
    availableScheduleBusinessHours: '営業時間',
    availableScheduleClearAll: 'すべてクリア',
    availableScheduleTimeColumn: '時間',
    availableScheduleClearDay: 'クリア',
    availableScheduleExceptions: '例外日',
    availableScheduleExceptionGuide: '週次グリッド下に特別な休業日やカスタム日程を設定してください。',
    availableScheduleAddException: '+ 例外を追加',
    availableScheduleExceptionClosed: '休業',
    availableScheduleExceptionCustomSlots: 'カスタムスロット',
    availableScheduleExceptionPeriodBlock: '期間不可',
    availableScheduleExceptionTimeBlock: '時間不可',
    availableScheduleExceptionAllDay: '終日',
    availableScheduleExceptionSpecificTime: '時間指定',
    availableScheduleExceptionStartDate: '開始日',
    availableScheduleExceptionEndDate: '終了日',
    availableScheduleExceptionDate: '日付',
    availableScheduleAddSlot: '+ スロット追加',
    availableScheduleSlotTo: '〜',
    availableScheduleSave: 'スケジュールを保存',
    reservationTimezone: 'タイムゾーン',
    signIn: 'サインイン',
    testLogin: 'テストログイン',
    testLoginBody:
      '一時ボタンでログイン状態とプロフィール遷移を手動確認します。',
    testMoveToLogin: 'ログイン画面へ戻る',
    testMoveToProfile: 'プロフィールへ移動',
    signOut: 'サインアウト',
    cancel: 'キャンセル',
    theme: 'テーマ',
    unlocked: 'サインイン済みのため保護設定を利用できます。',
    licenseCode: 'ライセンスコード',
    licenseAssigned: 'このライセンスはすでに別の塾で使用されています。',
    licenseExpired: 'このライセンスは期限切れです。',
    licenseNotFound: 'ライセンスコードが見つかりません。',
    licenseUnavailable: 'このライセンスは現在登録に使用できません。',
    licenseRenewUnavailable: 'ライセンスは有効期限前のみ延長できます。',
    requiredField: 'すべての項目を入力してください。',
    passwordMismatch: 'パスワードが一致しません。',
    signInFailed:
      '現在サインインできません。しばらくしてからもう一度お試しください。',
  },
  en: {
    academyCode: 'Academy Code',
    academyName: 'Academy Name',
    account: 'Account',
    adminMenu: 'Admin Menu',
    back: 'Back',
    academyMembers: 'Member Management',
    allChecks: 'Run All Health Checks',
    allChecksHint: 'Run local, Docker, and cloud checks in sequence.',
    cloud: 'Cloud Server',
    devClientLog: 'Emit Client Log',
    devClientLogHint:
      'Write one standard console.log entry from this client.',
    devServerLog: 'Emit Server Log',
    devServerLogHint:
      'Write one minimal-cost log entry from the development server.',
    devHealth: 'Developer / Status',
    devShowStudentSkinPreview: 'Show Student Skin Preview',
    devShowStudentSkinPreviewHint: 'Display the serialized student skin data for inspection.',
    devUnmountLoginContainer: 'Unmount Login Container',
    devUnmountLoginContainerHint:
      'Remove the login container from the tree when its toggle hides it.',
    devUnmountProfileContainer: 'Unmount Profile Container',
    devUnmountProfileContainerHint:
      'Remove the profile container from the tree when its toggle hides it.',
    devLicenseCreate: 'Create License',
    devLicenseCreateHint: 'Create one unassigned license.',
    devResult: 'Developer Action Result',
    devTableInit: 'Initialize Tables',
    devTableInitHint:
      'Recreate the managed tables and apply migrations in order.',
    devTableInitAndSeed: 'Initialize and Inject Test Data',
    devTableInitAndSeedHint:
      'Recreate the tables and then load the fixed Test Academy dataset.',
    dark: 'Dark',
    docker: 'Docker Server',
    env: 'Env',
    classroom: 'Classes',
    general: 'General',
    confirmPassword: 'Confirm Password',
    createAccount: 'Create Account',
    copyLicenseCode: 'Copy License Code',
    debugLog: 'Debug Log',
    displayName: 'Display Name',
    email: 'Email',
    edit: 'Edit',
    guestHint:
      'Sign in with the account you created to view your profile and protected controls.',
    invalid: 'The account ID or password is incorrect.',
    accountInactive: 'This account is inactive.',
    accountOnHold: 'This account is currently on hold.',
    accountPending: 'This account is pending approval.',
    academyInactive: 'The academy for this account is inactive.',
    academyCreateFailed:
      'We could not create the academy right now. Please try again.',
    duplicateLoginId:
      'That login ID is already in use. Please choose another one.',
    language: 'Language',
    lastChecked: 'Last checked',
    light: 'Light',
    local: 'Local Server',
    locked: 'Protected settings are currently locked.',
    loginNotice: 'Login Notice',
    login: 'Login',
    loginId: 'Login ID',
    loginIdPlaceholder: 'Login ID',
    members: 'Members',
    myInfo: 'My Info',
    pendingApproval: 'Join Approvals',
    preset: 'Preset Management',
    memberRegisterBody:
      'Submit a member account request and sign in after a root or admin approves it.',
    memberRegisterSuccess:
      'Your member registration request has been submitted. You can sign in after approval.',
    memberRole: 'Requested Role',
    memberRoleAdmin: 'Admin',
    memberRoleStudent: 'Student',
    memberRoleTeacher: 'Teacher',
    memberRoleInvalid: 'Please choose a valid role.',
    noAccount: 'No account has been created yet. Complete registration first.',
    note: 'Note',
    presetPlaceholderBody:
      'Preset editor placeholder. Detailed editing will be added later.',
    presetPlaceholderTitle: 'Preset',
    presetTitle: 'Preset List',
    presetNew: '+ New Preset',
    presetName: 'Preset Name',
    presetSave: 'Save Preset',
    presetDelete: 'Delete Preset',
    presetDeleteConfirm: 'Delete this preset?',
    presetShowDetails: 'Show Details',
    presetHideDetails: 'Show Summary',
    presetSummary: 'Summary',
    presetNoItems: 'No items available.',
    presetCategoryAll: 'All',
    presetSearch: 'Search',
    presetSearchPlaceholder: 'Search by item name or SKU',
    presetManualItemNamePlaceholder: 'Enter item name',
    presetManualAdd: 'Add Item',
    presetManualCategoryRequired: 'Select category',
    presetItemName: 'Item Name',
    presetSku: 'SKU',
    presetLch: 'L / C / H',
    presetCategoryBaseFoundation: 'Base / Foundation',
    presetCategoryBlush: 'Blush',
    presetCategoryLipColor: 'Lip Color',
    presetCategoryEyeshadow: 'Eyeshadow',
    presetCategoryContour: 'Contour',
    presetCategoryHighlighter: 'Highlighter',
    presetCategoryEtc: 'Etc.',
    profileEdit: 'Edit Profile',
    profileEditBody: 'Update the fields you need and save the profile.',
    profilePasswordPlaceholder: 'Leave blank to keep the current password.',
    profileSave: 'Save Profile',
    profileSaveSuccess: 'Profile updated successfully.',
    profileUpdateFailed:
      'We could not update the profile right now. Please try again.',
    profileStatusDenied: 'You do not have permission to change this status.',
    profileStatusInvalid: 'Please choose a valid status.',
    profileAuthPolicyDenied: 'Only root accounts can update auth policy.',
    status: 'Status',
    studentOptions: 'Student Profile',
    studentOptionsPlaceholderBody:
      'Review and edit skin values, skin traits, and preference points here.',
    studentOptionsPlaceholderTitle: 'Skin & Preferences',
    studentOptionsSkinData: 'Student Skin Data',
    studentOptionsMySkin: 'My Skin',
    studentOptionsTraits: 'Skin Traits',
    studentOptionsPreferencePoints: 'Preference Points',
    studentOptionsCategory: 'Category',
    studentOptionsActions: 'Actions',
    studentOptionsLightness: 'Lightness (L)',
    studentOptionsHue: 'Hue (H)',
    studentOptionsChroma: 'Chroma (C)',
    studentOptionsRangeRadius: 'Range Radius',
    studentOptionsSave: 'Save Student Skin',
    studentOptionsReset: 'Reset Draft',
    studentOptionsDone: 'Done',
    studentOptionsToolSelect: 'Select point',
    studentOptionsToolRange: 'Set range',
    studentOptionsZoom: 'Zoom',
    studentOptionsTraitsPlaceholder: 'Free memo for undertone, sensitivity, finish, or any other note.',
    studentOptionsNoTraits: 'No skin traits note yet.',
    studentOptionsNoPoints: 'No preference points set.',
    studentOptionsPoints: 'Points',
    studentOptionsDeleteTitle: 'Delete Point',
    studentOptionsDeleteMessage: 'Delete point {n}?',
    studentOptionsDeleteConfirm: 'Delete',
    studentOptionsUseFullSkinRange: 'Use full range on plane',
    statusActive: 'ACTIVE',
    statusHold: 'HOLD',
    statusInactive: 'INACTIVE',
    availableSchedulePlaceholderBody:
      'Available Schedule editor placeholder. Detailed editing will be added later.',
    availableSchedulePlaceholderTitle: 'Available Schedule',
    password: 'Password',
    passwordPlaceholder: 'Password',
    passwordSetupFailed:
      'We could not prepare your password right now. Please try again.',
    phone: 'Phone Number',
    profile: 'Profile',
    profileAcademy: 'Academy',
    profileBody: '',
    profileCodeAdmin: 'Admin Code',
    profileCodeStudent: 'Student Code',
    profileCodeTeacher: 'Teacher Code',
    profileId: 'Signed-in ID',
    profilePassword: 'Masked Password',
    profileRole: 'Role',
    protectedControls: 'Protected controls',
    protectedLocked: 'Locked until you sign in.',
    protectedSignin: 'Sign in to protected settings',
    protectedUnlocked:
      'Protected settings are available for the current account.',
    registerRoot: 'Root Register',
    registerRootBody:
      'Register the license, academy details, and root account in one flow.',
    registerType: 'Register Type',
    registerTypeUser: 'Member',
    registerTypeRoot: 'Root',
    inventory: 'Inventory',
    inventoryList: 'Inventory Management',
    inventoryAdd: 'Add Item',
    inventoryItemName: 'Item Name',
    inventorySku: 'SKU',
    inventoryBarcode: 'Barcode',
    inventoryCost: 'Cost',
    inventoryPrice: 'Price',
    inventoryColorL: 'L Value',
    inventoryColorC: 'C Value',
    inventoryColorH: 'H Value',
    inventoryStock: 'Stock',
    inventoryReorderLevel: 'Reorder Level',
    inventoryCategory: 'Category',
    inventorySupplier: 'Supplier',
    inventoryLocation: 'Storage Location',
    inventoryImageUrl: 'Image URL',
    inventoryNote: 'Note',
    inventoryStatusActive: 'Active',
    inventoryStatusInactive: 'Inactive',
    inventoryCategoryEtc: 'Etc.',
    inventoryNoItems: 'No inventory items yet.',
    inventoryAddTitle: 'Add Item',
    inventoryEdit: 'Edit',
    inventoryDelete: 'Delete',
    inventoryDeleteConfirmTitle: 'Delete Item',
    inventoryDeleteConfirmMessage: 'Delete {name}?',
    inventoryDeleteConfirm: 'Delete',
    inventorySave: 'Save',
    reservation: 'Class Booking',
    reservationPlaceholderBody:
      'Reservation placeholder. Booking flow will be added later.',
    reservationPlaceholderTitle: 'Reservation',
    reservationView: 'Booking Approval',
    reservationViewPlaceholderBody:
      'Reservation view placeholder. Teacher booking list will be added later.',
    reservationViewPlaceholderTitle: 'Reservation View',
    reservationTeacher: 'Your Teacher',
    reservationSelectDate: 'Select Date',
    reservationTimeSlots: 'Time Slots',
    reservationConfirm: 'Confirm Reservation',
    reservationDate: 'Date',
    reservationTime: 'Time',
    reservationBookLesson: 'Book Lesson',
    reservationBooked: 'Reservation Submitted',
    reservationBookedBody: 'Your reservation has been submitted and is awaiting confirmation.',
    reservationMyList: 'My Reservations',
    reservationNone: 'No reservations yet.',
    reservationSlotTaken: 'taken',
    reservationSlotBooked: 'booked',
    reservationStatusConfirmed: 'Confirmed',
    reservationStatusPending: 'Pending',
    reservationStatusCanceled: 'Canceled',
    reservationDetails: 'Details',
    reservationHideDetails: 'Hide Details',
    reservationPreset: 'Preset',
    reservationNote: 'Note',
    reservationCosmetics: 'Cosmetics',
    reservationNoCosmetics: 'No cosmetic items are linked to this reservation.',
    reservationViewApprove: 'Approve',
    reservationViewEmpty: 'No reservation requests yet.',
    reservationViewMismatchGuide:
      'Items outside the student preference range are shown in red, but approval is still allowed.',
    reservationViewNoPreference: 'No student preference is recorded for this category.',
    reservationViewPass: 'Pass',
    reservationViewPreferenceRanges: 'Preference Ranges',
    reservationViewPresetItems: 'Preset Item Check',
    reservationViewPending: 'Pending Requests',
    reservationViewCanceled: 'Canceled Reservations',
    reservationViewReject: 'Reject',
    reservationViewSkin: 'Skin',
    reservationViewStudent: 'Student',
    reservationViewTrait: 'Trait',
    reservationViewUpcoming: 'Confirmed Reservations',
    register: 'Register',
    registerBody: 'Choose a register type and enter the required information.',
    registerSuccess: 'Your root account has been created.',
    registrationBusy:
      'We could not complete registration right now. Please try again.',
    save: 'Save',
    result: 'Result',
    rootLoginId: 'Root Login ID',
    seedPasswordHint: 'Seed Password Rule',
    rootAlreadyExists: 'This academy already has a root account.',
    settings: 'Settings',
    availableSchedule: 'Teaching Availability',
    availableScheduleGuide: 'Paint the weekly grid to set available hours, then manage date-specific exceptions below.',
    availableScheduleTimezone: 'Schedule Timezone',
    availableScheduleWeeklyGrid: 'Weekly Grid',
    availableScheduleSlotsSelected: '{n} slots selected',
    availableScheduleBusinessHours: 'Business Hours',
    availableScheduleClearAll: 'Clear All',
    availableScheduleTimeColumn: 'Time',
    availableScheduleClearDay: 'clear',
    availableScheduleExceptions: 'Exceptions',
    availableScheduleExceptionGuide: 'Keep special closures or custom dates below the weekly board.',
    availableScheduleAddException: '+ Exception',
    availableScheduleExceptionClosed: 'Closed',
    availableScheduleExceptionCustomSlots: 'Custom Slots',
    availableScheduleExceptionPeriodBlock: 'Period Block',
    availableScheduleExceptionTimeBlock: 'Time Block',
    availableScheduleExceptionAllDay: 'All Day',
    availableScheduleExceptionSpecificTime: 'Specific Time',
    availableScheduleExceptionStartDate: 'Start Date',
    availableScheduleExceptionEndDate: 'End Date',
    availableScheduleExceptionDate: 'Date',
    availableScheduleAddSlot: '+ Slot',
    availableScheduleSlotTo: 'to',
    availableScheduleSave: 'Save Available Schedule',
    reservationTimezone: 'Timezone',
    signIn: 'Sign in',
    testLogin: 'Test Login',
    testLoginBody:
      'Use the temporary buttons to verify signed-in state and profile navigation manually.',
    testMoveToLogin: 'Back to Login',
    testMoveToProfile: 'Go to Profile',
    signOut: 'Sign out',
    cancel: 'Cancel',
    theme: 'Theme',
    unlocked: 'Protected settings are available because you are signed in.',
    licenseCode: 'License Code',
    licenseAssigned:
      'This license has already been assigned to another academy.',
    licenseExpired: 'This license has expired.',
    licenseNotFound: 'That license code could not be found.',
    licenseUnavailable: 'This license is not available for registration.',
    licenseRenewUnavailable:
      'This license can only be renewed before it expires.',
    requiredField: 'Fill in all fields.',
    passwordMismatch: 'Passwords do not match.',
    signInFailed: 'We could not sign you in right now. Please try again.',
  },
};
