import type { LanguageMode } from '../../../shared/shell-model';

export const MOBILE_SHELL_LABELS = {
  ja: {
    academyCode: '塾コード',
    academyName: '塾名',
    account: 'アカウント',
    back: '戻る',
    academyMembers: '所属メンバー',
    allChecks: '全ヘルスチェック実行',
    allChecksHint: 'ローカル、Docker、クラウドの順で確認します。',
    cloud: 'クラウドサーバー',
    devClientLog: 'クライアントログ出力',
    devClientLogHint:
      'このクライアントから標準の console.log を 1 件出力します。',
    devServerLog: 'サーバーログ出力',
    devServerLogHint:
      '開発サーバーで最小コストのログを 1 件出力します。',
    devHealth: '開発者オプション',
    devHealthBody: '現在のモバイルクライアントから各サーバー接続を確認します。',
    devUnmountLoginContainer: 'ログインコンテナをアンマウント',
    devUnmountLoginContainerHint:
      'ログイントグルで非表示時に login コンテナをツリーから外します。',
    devUnmountProfileContainer: 'プロフィールコンテナをアンマウント',
    devUnmountProfileContainerHint:
      'プロフィールトグルで非表示時に profile コンテナをツリーから外します。',
    devLicenseCreate: 'ライセンス生成',
    devLicenseCreateHint: '未割り当てライセンスを 1 件発行します。',
    devResult: '開発者アクション結果',
    devTableInit: 'テーブル初期化',
    devTableInitHint:
      '管理対象テーブルを再作成し、マイグレーションを順に適用します。',
    devTableInitAndSeed: 'テーブル初期化とテストデータ注入',
    devTableInitAndSeedHint:
      'テーブルを初期化したあと、Test Academy のテストデータをまとめて投入します。',
    dark: 'ダーク',
    docker: 'Dockerサーバー',
    env: '環境',
    general: '一般設定',
    confirmPassword: 'パスワード確認',
    createAccount: 'アカウント作成',
    copyLicenseCode: 'ライセンスコードをコピー',
    debugLog: 'デバッグログ',
    displayName: '表示名',
    email: 'メール',
    edit: '編集',
    guestHint:
      '登録したアカウントでログインするとプロフィールと保護コントロールを確認できます。',
    invalid: 'アカウントIDまたはパスワードが正しくありません。',
    accountInactive: 'このアカウントは無効です。',
    accountOnHold: 'このアカウントは現在保留中です。',
    accountPending: 'このアカウントは承認待ちです。',
    academyInactive: '所属塾は現在利用できません。',
    academyCreateFailed:
      '塾を作成できませんでした。しばらくしてからもう一度お試しください。',
    duplicateLoginId:
      'このログインIDは既に使用されています。別のIDを入力してください。',
    language: '言語',
    lastChecked: '最終確認',
    light: 'ライト',
    local: 'ローカルサーバー',
    locked: '保護設定は現在ロックされています。',
    loginNotice: 'ログイン案内',
    login: 'ログイン',
    loginId: 'ログインID',
    members: 'メンバー',
    pendingApproval: '承認待ち',
    preset: 'Preset',
    memberRegisterBody:
      'Member アカウントを申請すると、root または admin の承認後に利用できます。',
    memberRegisterSuccess:
      'Member 登録申請を送信しました。承認後にログインできます。',
    memberRole: '希望権限',
    memberRoleAdmin: 'Admin',
    memberRoleStudent: 'Student',
    memberRoleTeacher: 'Teacher',
    memberRoleInvalid: '有効な権限を選択してください。',
    noAccount:
      'まだ作成されたアカウントがありません。先に登録を完了してください。',
    note: 'メモ',
    presetPlaceholderBody: 'Preset editor placeholder. Detailed editing will be added later.',
    presetPlaceholderTitle: 'Preset',
    profileEdit: 'プロフィール編集',
    profileEditBody: '必要な項目を変更して保存できます。',
    profilePasswordPlaceholder: '空欄のままなら変更しません。',
    profileSave: 'プロフィール保存',
    profileSaveSuccess: 'プロフィールを更新しました。',
    profileUpdateFailed:
      'プロフィールを更新できませんでした。しばらくしてからもう一度お試しください。',
    profileStatusDenied: 'このアカウント状態は変更できません。',
    profileStatusInvalid: '有効な状態を選択してください。',
    profileAuthPolicyDenied: 'Auth Policy は root のみ変更できます。',
    status: '状態',
    studentOptions: 'Student Options',
    studentOptionsPlaceholderBody:
      'Student options placeholder. Skin values, skin traits, and preference ranges editing will be added later.',
    studentOptionsPlaceholderTitle: 'Student Options',
    statusActive: 'ACTIVE',
    statusHold: 'HOLD',
    statusInactive: 'INACTIVE',
    availableSchedulePlaceholderBody:
      'Available Schedule editor placeholder. Detailed editing will be added later.',
    availableSchedulePlaceholderTitle: 'Available Schedule',
    password: 'パスワード',
    passwordSetupFailed:
      'パスワードを準備できませんでした。しばらくしてからもう一度お試しください。',
    phone: '携帯番号',
    profile: 'プロフィール',
    profileAcademy: '所属塾',
    profileBody: '現在サインインしているアカウント情報です。',
    profileCodeAdmin: 'Admin Code',
    profileCodeStudent: 'Student Code',
    profileCodeTeacher: 'Teacher Code',
    profileId: 'サインイン中ID',
    profilePassword: 'マスクされたパスワード',
    profileRole: '権限',
    protectedControls: '保護コントロール',
    protectedLocked: 'サインインするまでロックされています。',
    protectedSignin: '保護設定にサインイン',
    protectedUnlocked: '現在のアカウントで保護設定を利用できます。',
    registerRoot: 'Root 登録',
    registerRootBody:
      'ライセンス、塾情報、root アカウント情報をまとめて登録します。',
    registerType: '登録タイプ',
    registerTypeUser: 'Member',
    registerTypeRoot: 'Root',
    reservation: '예약하기',
    reservationPlaceholderBody:
      'Reservation placeholder. Booking flow will be added later.',
    reservationPlaceholderTitle: '예약하기',
    reservationView: '예약보기',
    reservationViewPlaceholderBody:
      'Reservation view placeholder. Teacher booking list will be added later.',
    reservationViewPlaceholderTitle: '예약보기',
    register: '登録',
    registerBody: '登録タイプを選んで必要な情報を入力します。',
    registerSuccess: 'Root アカウントを作成しました。',
    registrationBusy:
      '現在登録を完了できません。しばらくしてからもう一度お試しください。',
    save: '保存',
    result: '結果',
    rootLoginId: 'root ログインID',
    rootAlreadyExists: 'この塾にはすでに root アカウントがあります。',
    settings: '設定',
    availableSchedule: 'Available Schedule',
    signIn: 'サインイン',
    testLogin: 'テストログイン',
    testLoginBody:
      '一時ボタンでログイン状態とプロフィール遷移を手動確認します。',
    testMoveToLogin: 'ログイン画面へ戻る',
    testMoveToProfile: 'プロフィールへ移動',
    signOut: 'サインアウト',
    cancel: 'キャンセル',
    theme: 'テーマ',
    unlocked: 'サインイン済みのため保護設定を利用できます。',
    licenseCode: 'ライセンスコード',
    licenseAssigned: 'このライセンスはすでに別の塾で使用されています。',
    licenseExpired: 'このライセンスは期限切れです。',
    licenseNotFound: 'ライセンスコードが見つかりません。',
    licenseUnavailable: 'このライセンスは現在登録に使用できません。',
    licenseRenewUnavailable: 'ライセンスは有効期限前のみ延長できます。',
    requiredField: 'すべての項目を入力してください。',
    passwordMismatch: 'パスワードが一致しません。',
    signInFailed:
      '現在サインインできません。しばらくしてからもう一度お試しください。',
  },
  en: {
    academyCode: 'Academy Code',
    academyName: 'Academy Name',
    account: 'Account',
    back: 'Back',
    academyMembers: 'Academy Members',
    allChecks: 'Run All Health Checks',
    allChecksHint: 'Run local, Docker, and cloud checks in sequence.',
    cloud: 'Cloud Server',
    devClientLog: 'Emit Client Log',
    devClientLogHint:
      'Write one standard console.log entry from this client.',
    devServerLog: 'Emit Server Log',
    devServerLogHint:
      'Write one minimal-cost log entry from the development server.',
    devHealth: 'Developer Options',
    devHealthBody: 'Check connectivity to each server from the mobile client.',
    devUnmountLoginContainer: 'Unmount Login Container',
    devUnmountLoginContainerHint:
      'Remove the login container from the tree when its toggle hides it.',
    devUnmountProfileContainer: 'Unmount Profile Container',
    devUnmountProfileContainerHint:
      'Remove the profile container from the tree when its toggle hides it.',
    devLicenseCreate: 'Create License',
    devLicenseCreateHint: 'Create one unassigned license.',
    devResult: 'Developer Action Result',
    devTableInit: 'Initialize Tables',
    devTableInitHint:
      'Recreate the managed tables and apply migrations in order.',
    devTableInitAndSeed: 'Initialize and Inject Test Data',
    devTableInitAndSeedHint:
      'Recreate the tables and then load the fixed Test Academy dataset.',
    dark: 'Dark',
    docker: 'Docker Server',
    env: 'Env',
    general: 'General',
    confirmPassword: 'Confirm Password',
    createAccount: 'Create Account',
    copyLicenseCode: 'Copy License Code',
    debugLog: 'Debug Log',
    displayName: 'Display Name',
    email: 'Email',
    edit: 'Edit',
    guestHint:
      'Sign in with the account you created to view your profile and protected controls.',
    invalid: 'The account ID or password is incorrect.',
    accountInactive: 'This account is inactive.',
    accountOnHold: 'This account is currently on hold.',
    accountPending: 'This account is pending approval.',
    academyInactive: 'The academy for this account is inactive.',
    academyCreateFailed:
      'We could not create the academy right now. Please try again.',
    duplicateLoginId:
      'That login ID is already in use. Please choose another one.',
    language: 'Language',
    lastChecked: 'Last checked',
    light: 'Light',
    local: 'Local Server',
    locked: 'Protected settings are currently locked.',
    loginNotice: 'Login Notice',
    login: 'Login',
    loginId: 'Login ID',
    members: 'Members',
    pendingApproval: 'Pending Approval',
    preset: 'Preset',
    memberRegisterBody:
      'Submit a member account request and sign in after a root or admin approves it.',
    memberRegisterSuccess:
      'Your member registration request has been submitted. You can sign in after approval.',
    memberRole: 'Requested Role',
    memberRoleAdmin: 'Admin',
    memberRoleStudent: 'Student',
    memberRoleTeacher: 'Teacher',
    memberRoleInvalid: 'Please choose a valid role.',
    noAccount: 'No account has been created yet. Complete registration first.',
    note: 'Note',
    presetPlaceholderBody:
      'Preset editor placeholder. Detailed editing will be added later.',
    presetPlaceholderTitle: 'Preset',
    profileEdit: 'Edit Profile',
    profileEditBody: 'Update the fields you need and save the profile.',
    profilePasswordPlaceholder: 'Leave blank to keep the current password.',
    profileSave: 'Save Profile',
    profileSaveSuccess: 'Profile updated successfully.',
    profileUpdateFailed:
      'We could not update the profile right now. Please try again.',
    profileStatusDenied: 'You do not have permission to change this status.',
    profileStatusInvalid: 'Please choose a valid status.',
    profileAuthPolicyDenied: 'Only root accounts can update auth policy.',
    status: 'Status',
    studentOptions: 'Student Options',
    studentOptionsPlaceholderBody:
      'Student options placeholder. Skin values, skin traits, and preference ranges editing will be added later.',
    studentOptionsPlaceholderTitle: 'Student Options',
    statusActive: 'ACTIVE',
    statusHold: 'HOLD',
    statusInactive: 'INACTIVE',
    availableSchedulePlaceholderBody:
      'Available Schedule editor placeholder. Detailed editing will be added later.',
    availableSchedulePlaceholderTitle: 'Available Schedule',
    password: 'Password',
    passwordSetupFailed:
      'We could not prepare your password right now. Please try again.',
    phone: 'Phone Number',
    profile: 'Profile',
    profileAcademy: 'Academy',
    profileBody: 'This is the account currently signed in.',
    profileCodeAdmin: 'Admin Code',
    profileCodeStudent: 'Student Code',
    profileCodeTeacher: 'Teacher Code',
    profileId: 'Signed-in ID',
    profilePassword: 'Masked Password',
    profileRole: 'Role',
    protectedControls: 'Protected controls',
    protectedLocked: 'Locked until you sign in.',
    protectedSignin: 'Sign in to protected settings',
    protectedUnlocked:
      'Protected settings are available for the current account.',
    registerRoot: 'Root Register',
    registerRootBody:
      'Register the license, academy details, and root account in one flow.',
    registerType: 'Register Type',
    registerTypeUser: 'Member',
    registerTypeRoot: 'Root',
    reservation: 'Reservation',
    reservationPlaceholderBody:
      'Reservation placeholder. Booking flow will be added later.',
    reservationPlaceholderTitle: 'Reservation',
    reservationView: 'Reservation View',
    reservationViewPlaceholderBody:
      'Reservation view placeholder. Teacher booking list will be added later.',
    reservationViewPlaceholderTitle: 'Reservation View',
    register: 'Register',
    registerBody: 'Choose a register type and enter the required information.',
    registerSuccess: 'Your root account has been created.',
    registrationBusy:
      'We could not complete registration right now. Please try again.',
    save: 'Save',
    result: 'Result',
    rootLoginId: 'Root Login ID',
    rootAlreadyExists: 'This academy already has a root account.',
    settings: 'Settings',
    availableSchedule: 'Available Schedule',
    signIn: 'Sign in',
    testLogin: 'Test Login',
    testLoginBody:
      'Use the temporary buttons to verify signed-in state and profile navigation manually.',
    testMoveToLogin: 'Back to Login',
    testMoveToProfile: 'Go to Profile',
    signOut: 'Sign out',
    cancel: 'Cancel',
    theme: 'Theme',
    unlocked: 'Protected settings are available because you are signed in.',
    licenseCode: 'License Code',
    licenseAssigned:
      'This license has already been assigned to another academy.',
    licenseExpired: 'This license has expired.',
    licenseNotFound: 'That license code could not be found.',
    licenseUnavailable: 'This license is not available for registration.',
    licenseRenewUnavailable:
      'This license can only be renewed before it expires.',
    requiredField: 'Fill in all fields.',
    passwordMismatch: 'Passwords do not match.',
    signInFailed: 'We could not sign you in right now. Please try again.',
  },
} as const;

export function getMobileShellLabels(language: LanguageMode) {
  return MOBILE_SHELL_LABELS[language];
}


