import {StyleSheet} from 'react-native';

export const mobileShellStyles = StyleSheet.create({
  safeArea: {flex: 1},
  screen: {flex: 1},
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  menuButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuIconFrame: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuIconLayer: {position: 'absolute'},
  menuButtonLabel: {fontSize: 18, fontWeight: '800'},
  menuCloseLabel: {fontSize: 24, fontWeight: '500', lineHeight: 24},
  topBarTitle: {fontSize: 22, fontWeight: '800'},
  body: {flex: 1, padding: 16},
  menuSurface: {
    flex: 1,
    margin: -16,
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  stack: {gap: 16, paddingBottom: 24},
  card: {padding: 18, borderRadius: 22, borderWidth: 1},
  cardTitle: {fontSize: 20, fontWeight: '800', marginBottom: 8},
  bodyText: {fontSize: 14, lineHeight: 22},
  bodyStrong: {fontSize: 14, fontWeight: '700', lineHeight: 22, marginTop: 10},
  fieldLabel: {fontSize: 13, fontWeight: '700', marginTop: 14, marginBottom: 8},
  optionRow: {flexDirection: 'row', gap: 10, flexWrap: 'wrap'},
  optionChip: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 999,
    borderWidth: 1,
  },
  optionChipText: {fontSize: 14, fontWeight: '800'},
  input: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  errorText: {color: '#bc4749', fontSize: 13, fontWeight: '700', marginTop: 12},
  actionButton: {paddingHorizontal: 16, paddingVertical: 12, borderRadius: 16},
  actionText: {fontSize: 14, fontWeight: '800'},
  primaryAction: {padding: 18, borderRadius: 22},
  primaryActionTitle: {fontSize: 18, fontWeight: '800', marginBottom: 6},
  primaryActionHint: {fontSize: 13, lineHeight: 18},
  resultPanel: {marginTop: 12, padding: 16, borderRadius: 18},
  resultLabel: {fontSize: 12, fontWeight: '800', letterSpacing: 1, marginBottom: 8},
  metaText: {fontSize: 12, lineHeight: 18, marginTop: 8},
  overlayItem: {
    borderRadius: 18,
    height: 56,
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  overlayItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  overlayItemText: {fontSize: 18, fontWeight: '800'},
  overlayItemTextActive: {fontSize: 24},
  overlayItemTextInactive: {fontSize: 16},
  overlayItemIndicator: {fontSize: 18, fontWeight: '800'},
  overlaySubItem: {
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  overlaySubmenu: {
    overflow: 'hidden',
  },
  overlaySubItemText: {fontSize: 16, fontWeight: '700'},
  overlaySubItemTextActive: {fontSize: 17},
  overlaySubItemTextInactive: {fontSize: 16},
  overlayItemSpaced: {marginTop: 18},
});
