-- MAME 塾本体テーブル
CREATE TABLE MAME_ACADEMIES (
    ACADEMY_ID NUMBER(19, 0) NOT NULL,
    ACADEMY_CODE VARCHAR2(12 CHAR) NOT NULL,
    ACADEMY_NAME VARCHAR2(100 CHAR) NOT NULL,
    STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    DELETED_AT TIMESTAMP(6),
    CONSTRAINT PK_MAME_ACADEMIES PRIMARY KEY (ACADEMY_ID),
    CONSTRAINT UQ_MAME_ACADEMIES_CODE UNIQUE (ACADEMY_CODE),
    CONSTRAINT UQ_MAME_ACADEMIES_NAME UNIQUE (ACADEMY_NAME),
    CONSTRAINT CK_MAME_ACADEMIES_STATUS_CODE CHECK (STATUS_CODE IN ('ACTIVE', 'INACTIVE', 'HOLD'))
);

-- 数値ベースの塾内部主キー採番用シーケンス
CREATE SEQUENCE MAME_ACADEMIES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- INSERT 時に塾の主キーと塾コードを自動採番するトリガー
CREATE OR REPLACE TRIGGER MAME_ACADEMIES_BIR
BEFORE INSERT ON MAME_ACADEMIES
FOR EACH ROW
BEGIN
    IF :NEW.ACADEMY_ID IS NULL THEN
        SELECT MAME_ACADEMIES_SEQ.NEXTVAL
          INTO :NEW.ACADEMY_ID
          FROM DUAL;
    END IF;

    IF :NEW.ACADEMY_CODE IS NULL THEN -- fallbackハンドリング必要
        SELECT LOWER(SUBSTR(STANDARD_HASH(RAWTOHEX(SYS_GUID()), 'SHA256'), 1, 12))
          INTO :NEW.ACADEMY_CODE
          FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

-- UPDATE 時に更新日時を自動更新するトリガー
CREATE OR REPLACE TRIGGER MAME_ACADEMIES_BUR
BEFORE UPDATE ON MAME_ACADEMIES
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- 塾コードの変更を禁止するトリガー
CREATE OR REPLACE TRIGGER MAME_ACADEMIES_BUC
BEFORE UPDATE OF ACADEMY_CODE ON MAME_ACADEMIES
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'ACADEMY_CODE is immutable.');
END;
/

-- 塾ステータス検索用インデックス
CREATE INDEX IDX_MAME_ACADEMIES_STATUS_CODE
    ON MAME_ACADEMIES (STATUS_CODE);
