-- MAIMEI 塾本体テーブル
CREATE TABLE MAIMEI_ACADEMIES (
    ACADEMY_ID NUMBER(19, 0) NOT NULL,
    ACADEMY_CODE VARCHAR2(12 CHAR) NOT NULL,
    ACADEMY_NAME VARCHAR2(100 CHAR) NOT NULL,
    STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    DELETED_AT TIMESTAMP(6),
    CONSTRAINT PK_MAIMEI_ACADEMIES PRIMARY KEY (ACADEMY_ID),
    CONSTRAINT UQ_MAIMEI_ACADEMIES_CODE UNIQUE (ACADEMY_CODE),
    CONSTRAINT UQ_MAIMEI_ACADEMIES_NAME UNIQUE (ACADEMY_NAME),
    CONSTRAINT CK_MAIMEI_ACADEMIES_STATUS_CODE CHECK (STATUS_CODE IN ('ACTIVE', 'INACTIVE', 'HOLD'))
);

COMMENT ON COLUMN MAIMEI_ACADEMIES.ACADEMY_ID IS '塾の数値ベース内部主キー';
COMMENT ON COLUMN MAIMEI_ACADEMIES.ACADEMY_CODE IS '塾を外部から識別する不変コード';
COMMENT ON COLUMN MAIMEI_ACADEMIES.ACADEMY_NAME IS '塾の表示名';
COMMENT ON COLUMN MAIMEI_ACADEMIES.STATUS_CODE IS '塾の運営状態コード';
COMMENT ON COLUMN MAIMEI_ACADEMIES.CREATED_AT IS '初回作成日時';
COMMENT ON COLUMN MAIMEI_ACADEMIES.CREATED_BY IS '初回作成者';
COMMENT ON COLUMN MAIMEI_ACADEMIES.UPDATED_AT IS '最終更新日時';
COMMENT ON COLUMN MAIMEI_ACADEMIES.UPDATED_BY IS '最終更新者';
COMMENT ON COLUMN MAIMEI_ACADEMIES.DELETED_AT IS '論理削除日時';

-- 数値ベースの塾内部主キー採番用シーケンス
CREATE SEQUENCE MAIMEI_ACADEMIES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- INSERT 時に塾の主キーと塾コードを自動採番するトリガー
CREATE OR REPLACE TRIGGER MAIMEI_ACADEMIES_BIR
BEFORE INSERT ON MAIMEI_ACADEMIES
FOR EACH ROW
BEGIN
    IF :NEW.ACADEMY_ID IS NULL THEN
        SELECT MAIMEI_ACADEMIES_SEQ.NEXTVAL
          INTO :NEW.ACADEMY_ID
          FROM DUAL;
    END IF;

    IF :NEW.ACADEMY_CODE IS NULL THEN -- fallbackハンドリング必要
        SELECT LOWER(SUBSTR(STANDARD_HASH(RAWTOHEX(SYS_GUID()), 'SHA256'), 1, 12))
          INTO :NEW.ACADEMY_CODE
          FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

-- UPDATE 時に更新日時を自動更新するトリガー
CREATE OR REPLACE TRIGGER MAIMEI_ACADEMIES_BUR
BEFORE UPDATE ON MAIMEI_ACADEMIES
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- 塾コードの変更を禁止するトリガー
CREATE OR REPLACE TRIGGER MAIMEI_ACADEMIES_BUC
BEFORE UPDATE OF ACADEMY_CODE ON MAIMEI_ACADEMIES
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'ACADEMY_CODE is immutable.');
END;
/

-- 塾ステータス検索用インデックス
CREATE INDEX IDX_MAIMEI_ACADEMIES_STATUS_CODE
    ON MAIMEI_ACADEMIES (STATUS_CODE);
