ALTER TABLE MAIMEI_TEACHERS MODIFY (ACADEMY_CODE NULL);

ALTER TABLE MAIMEI_TEACHERS DROP CONSTRAINT CK_MAIMEI_TEACHERS_STATUS_CODE;

ALTER TABLE MAIMEI_TEACHERS ADD CONSTRAINT CK_MAIMEI_TEACHERS_STATUS_CODE
    CHECK (STATUS_CODE IN ('PENDING', 'ACTIVE', 'INACTIVE', 'HOLD'));

ALTER TABLE MAIMEI_TEACHERS ADD CONSTRAINT CK_MAIMEI_TEACHERS_PENDING_ACADEMY
    CHECK (
        (STATUS_CODE = 'PENDING' AND ACADEMY_CODE IS NULL)
        OR (STATUS_CODE IN ('ACTIVE', 'INACTIVE', 'HOLD') AND ACADEMY_CODE IS NOT NULL)
    );

ALTER TABLE MAIMEI_STAFF MODIFY (ACADEMY_CODE NULL);

ALTER TABLE MAIMEI_STAFF DROP CONSTRAINT CK_MAIMEI_STAFF_STATUS_CODE;

ALTER TABLE MAIMEI_STAFF ADD CONSTRAINT CK_MAIMEI_STAFF_STATUS_CODE
    CHECK (STATUS_CODE IN ('PENDING', 'ACTIVE', 'INACTIVE', 'HOLD'));

ALTER TABLE MAIMEI_STAFF ADD CONSTRAINT CK_MAIMEI_STAFF_PENDING_ACADEMY
    CHECK (
        (ROLE_CODE = 'ROOT' AND STATUS_CODE IN ('ACTIVE', 'INACTIVE', 'HOLD') AND ACADEMY_CODE IS NOT NULL)
        OR (ROLE_CODE = 'ADMIN' AND STATUS_CODE = 'PENDING' AND ACADEMY_CODE IS NULL)
        OR (ROLE_CODE = 'ADMIN' AND STATUS_CODE IN ('ACTIVE', 'INACTIVE', 'HOLD') AND ACADEMY_CODE IS NOT NULL)
    );
