-- MAIMEI 学生テーブル
CREATE TABLE MAIMEI_STUDENTS (
    STUDENT_ID NUMBER(19, 0) NOT NULL,
    STUDENT_CODE VARCHAR2(12 CHAR) NOT NULL,
    ACADEMY_CODE VARCHAR2(12 CHAR),
    LOGIN_ID VARCHAR2(100 CHAR) NOT NULL,
    PASSWORD_HASH VARCHAR2(255 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(100 CHAR) NOT NULL,
    EMAIL VARCHAR2(255 CHAR),
    PHONE VARCHAR2(30 CHAR) NOT NULL,
    SKIN_L_VALUE NUMBER(10, 4),
    SKIN_C_VALUE NUMBER(10, 4),
    SKIN_H_VALUE NUMBER(10, 4),
    SKIN_TRAITS_BODY CLOB,
    PREFERENCE_RANGES_BODY CLOB,
    PRIMARY_TEACHER_ID NUMBER(19, 0),
    PASS_TOTAL_COUNT NUMBER(10, 0) DEFAULT 0 NOT NULL,
    PASS_REMAINING_COUNT NUMBER(10, 0) DEFAULT 0 NOT NULL,
    PASS_LAST_USED_AT TIMESTAMP(6),
    PASS_EXPIRES_AT TIMESTAMP(6),
    NOTE_BODY CLOB,
    STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
    LAST_LOGIN_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    DELETED_AT TIMESTAMP(6),
    CONSTRAINT PK_MAIMEI_STUDENTS PRIMARY KEY (STUDENT_ID),
    CONSTRAINT UQ_MAIMEI_STUDENTS_CODE UNIQUE (STUDENT_CODE),
    CONSTRAINT UQ_MAIMEI_STUDENTS_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UQ_MAIMEI_STUDENTS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_MAIMEI_STUDENTS_ACADEMY_CODE FOREIGN KEY (ACADEMY_CODE)
        REFERENCES MAIMEI_ACADEMIES (ACADEMY_CODE),
    CONSTRAINT FK_MAIMEI_STUDENTS_PRIMARY_TEACHER_ID FOREIGN KEY (PRIMARY_TEACHER_ID)
        REFERENCES MAIMEI_TEACHERS (TEACHER_ID),
    CONSTRAINT CK_MAIMEI_STUDENTS_STATUS_CODE CHECK (STATUS_CODE IN ('PENDING', 'ACTIVE', 'INACTIVE', 'HOLD')),
    CONSTRAINT CK_MAIMEI_STUDENTS_PENDING_ACADEMY CHECK (
        (STATUS_CODE = 'PENDING' AND ACADEMY_CODE IS NULL)
        OR (STATUS_CODE IN ('ACTIVE', 'INACTIVE', 'HOLD'))
    ),
    CONSTRAINT CK_MAIMEI_STUDENTS_PASS_COUNTS CHECK (
        PASS_TOTAL_COUNT >= 0
        AND PASS_REMAINING_COUNT >= 0
        AND PASS_REMAINING_COUNT <= PASS_TOTAL_COUNT
    ),
    CONSTRAINT CK_MAIMEI_STUDENTS_PASS_EXPIRES CHECK (
        PASS_EXPIRES_AT IS NULL OR PASS_LAST_USED_AT IS NULL OR PASS_EXPIRES_AT >= PASS_LAST_USED_AT
    )
);

COMMENT ON COLUMN MAIMEI_STUDENTS.STUDENT_ID IS '学生の数値ベース内部主キー';
COMMENT ON COLUMN MAIMEI_STUDENTS.STUDENT_CODE IS '学生を外部から識別する不変コード';
COMMENT ON COLUMN MAIMEI_STUDENTS.ACADEMY_CODE IS '所属塾コード。承認前はNULL許可';
COMMENT ON COLUMN MAIMEI_STUDENTS.LOGIN_ID IS 'ログインに使用する一意ID';
COMMENT ON COLUMN MAIMEI_STUDENTS.PASSWORD_HASH IS 'パスワードハッシュ値';
COMMENT ON COLUMN MAIMEI_STUDENTS.DISPLAY_NAME IS '学生表示名';
COMMENT ON COLUMN MAIMEI_STUDENTS.EMAIL IS '学生メールアドレス';
COMMENT ON COLUMN MAIMEI_STUDENTS.PHONE IS '学生携帯電話番号';
COMMENT ON COLUMN MAIMEI_STUDENTS.SKIN_L_VALUE IS '学生代表肌色のL値';
COMMENT ON COLUMN MAIMEI_STUDENTS.SKIN_C_VALUE IS '学生代表肌色のC値';
COMMENT ON COLUMN MAIMEI_STUDENTS.SKIN_H_VALUE IS '学生代表肌色のH値';
COMMENT ON COLUMN MAIMEI_STUDENTS.SKIN_TRAITS_BODY IS '肌特性の記録本文';
COMMENT ON COLUMN MAIMEI_STUDENTS.PREFERENCE_RANGES_BODY IS '好みの範囲情報本文';
COMMENT ON COLUMN MAIMEI_STUDENTS.PRIMARY_TEACHER_ID IS '現在の主担当講師ID';
COMMENT ON COLUMN MAIMEI_STUDENTS.PASS_TOTAL_COUNT IS '受講券の総回数';
COMMENT ON COLUMN MAIMEI_STUDENTS.PASS_REMAINING_COUNT IS '受講券の残回数';
COMMENT ON COLUMN MAIMEI_STUDENTS.PASS_LAST_USED_AT IS '最後に受講券を使用した日時';
COMMENT ON COLUMN MAIMEI_STUDENTS.PASS_EXPIRES_AT IS '受講券の有効期限';
COMMENT ON COLUMN MAIMEI_STUDENTS.NOTE_BODY IS '学生に関する自由記述メモ';
COMMENT ON COLUMN MAIMEI_STUDENTS.STATUS_CODE IS '学生状態コード';
COMMENT ON COLUMN MAIMEI_STUDENTS.LAST_LOGIN_AT IS '最終ログイン日時';
COMMENT ON COLUMN MAIMEI_STUDENTS.CREATED_AT IS '初回作成日時';
COMMENT ON COLUMN MAIMEI_STUDENTS.CREATED_BY IS '初回作成者';
COMMENT ON COLUMN MAIMEI_STUDENTS.UPDATED_AT IS '最終更新日時';
COMMENT ON COLUMN MAIMEI_STUDENTS.UPDATED_BY IS '最終更新者';
COMMENT ON COLUMN MAIMEI_STUDENTS.DELETED_AT IS '論理削除日時';

CREATE SEQUENCE MAIMEI_STUDENTS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE MAIMEI_STUDENT_CODE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER MAIMEI_STUDENTS_BIR
BEFORE INSERT ON MAIMEI_STUDENTS
FOR EACH ROW
BEGIN
    IF :NEW.STUDENT_ID IS NULL THEN
        SELECT MAIMEI_STUDENTS_SEQ.NEXTVAL
          INTO :NEW.STUDENT_ID
          FROM DUAL;
    END IF;

    IF :NEW.STUDENT_CODE IS NULL THEN
        SELECT 'ST' || LPAD(MAIMEI_STUDENT_CODE_SEQ.NEXTVAL, 10, '0')
          INTO :NEW.STUDENT_CODE
          FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_STUDENTS_BUR
BEFORE UPDATE ON MAIMEI_STUDENTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_STUDENTS_BUC
BEFORE UPDATE OF STUDENT_CODE ON MAIMEI_STUDENTS
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'STUDENT_CODE is immutable.');
END;
/

CREATE INDEX IDX_MAIMEI_STUDENTS_ACADEMY_CODE
    ON MAIMEI_STUDENTS (ACADEMY_CODE);

CREATE INDEX IDX_MAIMEI_STUDENTS_STATUS_CODE
    ON MAIMEI_STUDENTS (STATUS_CODE);

CREATE INDEX IDX_MAIMEI_STUDENTS_PHONE
    ON MAIMEI_STUDENTS (PHONE);

CREATE INDEX IDX_MAIMEI_STUDENTS_DISPLAY_NAME
    ON MAIMEI_STUDENTS (DISPLAY_NAME);

CREATE INDEX IDX_MAIMEI_STUDENTS_PRIMARY_TEACHER_ID
    ON MAIMEI_STUDENTS (PRIMARY_TEACHER_ID);
