-- MAME ユーザーテーブル
CREATE TABLE MAME_USERS (
    USER_ID NUMBER(19, 0) NOT NULL,
    ACADEMY_CODE VARCHAR2(12 CHAR),
    USER_CODE VARCHAR2(7 CHAR) NOT NULL,
    LOGIN_ID VARCHAR2(100 CHAR) NOT NULL,
    EMAIL VARCHAR2(255 CHAR),
    DISPLAY_NAME VARCHAR2(100 CHAR) NOT NULL,
    PASSWORD_HASH VARCHAR2(255 CHAR) NOT NULL,
    ROLE_CODE VARCHAR2(30 CHAR) NOT NULL,
    STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    LAST_LOGIN_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    DELETED_AT TIMESTAMP(6),
    CONSTRAINT PK_MAME_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_MAME_USERS_CODE UNIQUE (USER_CODE),
    CONSTRAINT UQ_MAME_USERS_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UQ_MAME_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_MAME_USERS_ACADEMY_CODE FOREIGN KEY (ACADEMY_CODE)
        REFERENCES MAME_ACADEMIES (ACADEMY_CODE),
    CONSTRAINT CK_MAME_USERS_ROLE_CODE CHECK (ROLE_CODE IN ('ROOT', 'ADMIN', 'TEACHER', 'STUDENT')),
    CONSTRAINT CK_MAME_USERS_STATUS_CODE CHECK (STATUS_CODE IN ('PENDING', 'ACTIVE', 'INACTIVE', 'HOLD'))
);

-- 数値ベースの内部主キー採番用シーケンス
CREATE SEQUENCE MAME_USERS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 固定長のユーザーコード採番用シーケンス
CREATE SEQUENCE MAME_USER_CODE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- INSERT 時に主キーと監査日時の初期値を補完するトリガー
CREATE OR REPLACE TRIGGER MAME_USERS_BIR
BEFORE INSERT ON MAME_USERS
FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        SELECT MAME_USERS_SEQ.NEXTVAL
          INTO :NEW.USER_ID
          FROM DUAL;
    END IF;

    IF :NEW.USER_CODE IS NULL THEN
        SELECT CASE :NEW.ROLE_CODE
                   WHEN 'ROOT' THEN 'R'
                   WHEN 'ADMIN' THEN 'A'
                   WHEN 'TEACHER' THEN 'T'
                   WHEN 'STUDENT' THEN 'S'
               END || LPAD(MAME_USER_CODE_SEQ.NEXTVAL, 6, '0')
          INTO :NEW.USER_CODE
          FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

-- UPDATE 時に更新日時を自動更新するトリガー
CREATE OR REPLACE TRIGGER MAME_USERS_BUR
BEFORE UPDATE ON MAME_USERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- 役割別検索用インデックス
CREATE INDEX IDX_MAME_USERS_ROLE_CODE
    ON MAME_USERS (ROLE_CODE);

-- 塾コード検索用インデックス
CREATE INDEX IDX_MAME_USERS_ACADEMY_CODE
    ON MAME_USERS (ACADEMY_CODE);

-- ステータス別検索用インデックス
CREATE INDEX IDX_MAME_USERS_STATUS_CODE
    ON MAME_USERS (STATUS_CODE);

-- 塾内ロール検索用複合インデックス
CREATE INDEX IDX_MAME_USERS_ACADEMY_ROLE
    ON MAME_USERS (ACADEMY_CODE, ROLE_CODE);

-- 学園ごとに ROOT ユーザーを 1 件に制限する関数ベース一意インデックス
CREATE UNIQUE INDEX UQ_MAME_USERS_ROOT_PER_ACADEMY
    ON MAME_USERS (
        CASE
            WHEN ROLE_CODE = 'ROOT' AND ACADEMY_CODE IS NOT NULL THEN ACADEMY_CODE
        END
    );
