-- MAIMEI ログイン専用アカウントテーブル
CREATE TABLE MAIMEI_ACCOUNTS (
    ACCOUNT_ID NUMBER(19, 0) NOT NULL,
    LOGIN_ID VARCHAR2(100 CHAR) NOT NULL,
    PASSWORD_HASH VARCHAR2(255 CHAR) NOT NULL,
    ROLE_CODE VARCHAR2(30 CHAR) NOT NULL,
    STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    STAFF_ID NUMBER(19, 0),
    TEACHER_ID NUMBER(19, 0),
    STUDENT_ID NUMBER(19, 0),
    LAST_LOGIN_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    DELETED_AT TIMESTAMP(6),
    CONSTRAINT PK_MAIMEI_ACCOUNTS PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT UQ_MAIMEI_ACCOUNTS_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UQ_MAIMEI_ACCOUNTS_STAFF_ID UNIQUE (STAFF_ID),
    CONSTRAINT UQ_MAIMEI_ACCOUNTS_TEACHER_ID UNIQUE (TEACHER_ID),
    CONSTRAINT UQ_MAIMEI_ACCOUNTS_STUDENT_ID UNIQUE (STUDENT_ID),
    CONSTRAINT FK_MAIMEI_ACCOUNTS_STAFF_ID FOREIGN KEY (STAFF_ID)
        REFERENCES MAIMEI_STAFF (STAFF_ID),
    CONSTRAINT FK_MAIMEI_ACCOUNTS_TEACHER_ID FOREIGN KEY (TEACHER_ID)
        REFERENCES MAIMEI_TEACHERS (TEACHER_ID),
    CONSTRAINT FK_MAIMEI_ACCOUNTS_STUDENT_ID FOREIGN KEY (STUDENT_ID)
        REFERENCES MAIMEI_STUDENTS (STUDENT_ID),
    CONSTRAINT CK_MAIMEI_ACCOUNTS_ROLE_CODE CHECK (ROLE_CODE IN ('ROOT', 'ADMIN', 'TEACHER', 'STUDENT')),
    CONSTRAINT CK_MAIMEI_ACCOUNTS_STATUS_CODE CHECK (STATUS_CODE IN ('ACTIVE', 'INACTIVE', 'HOLD')),
    CONSTRAINT CK_MAIMEI_ACCOUNTS_ROLE_TARGET CHECK (
        (ROLE_CODE IN ('ROOT', 'ADMIN') AND STAFF_ID IS NOT NULL AND TEACHER_ID IS NULL AND STUDENT_ID IS NULL)
        OR (ROLE_CODE = 'TEACHER' AND STAFF_ID IS NULL AND TEACHER_ID IS NOT NULL AND STUDENT_ID IS NULL)
        OR (ROLE_CODE = 'STUDENT' AND STAFF_ID IS NULL AND TEACHER_ID IS NULL AND STUDENT_ID IS NOT NULL)
    )
);

COMMENT ON COLUMN MAIMEI_ACCOUNTS.ACCOUNT_ID IS 'ログインアカウントの数値ベース内部主キー';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.LOGIN_ID IS 'ログインに使用する一意ID';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.PASSWORD_HASH IS 'パスワードハッシュ値';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.ROLE_CODE IS 'アカウント役割コード(ROOT, ADMIN, TEACHER, STUDENT)';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.STATUS_CODE IS 'アカウント状態コード';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.STAFF_ID IS 'ROLE_CODEがROOTまたはADMINのときに接続されるスタッフID';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.TEACHER_ID IS 'ROLE_CODEがTEACHERのときに接続される講師ID';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.STUDENT_ID IS 'ROLE_CODEがSTUDENTのときに接続される学生ID';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.LAST_LOGIN_AT IS '最終ログイン日時';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.CREATED_AT IS '初回作成日時';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.CREATED_BY IS '初回作成者';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.UPDATED_AT IS '最終更新日時';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.UPDATED_BY IS '最終更新者';
COMMENT ON COLUMN MAIMEI_ACCOUNTS.DELETED_AT IS '論理削除日時';

CREATE SEQUENCE MAIMEI_ACCOUNTS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER MAIMEI_ACCOUNTS_BIR
BEFORE INSERT ON MAIMEI_ACCOUNTS
FOR EACH ROW
BEGIN
    IF :NEW.ACCOUNT_ID IS NULL THEN
        SELECT MAIMEI_ACCOUNTS_SEQ.NEXTVAL
          INTO :NEW.ACCOUNT_ID
          FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_ACCOUNTS_BUR
BEFORE UPDATE ON MAIMEI_ACCOUNTS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_ACCOUNTS_BUC
BEFORE UPDATE OF LOGIN_ID, ROLE_CODE, STAFF_ID, TEACHER_ID, STUDENT_ID ON MAIMEI_ACCOUNTS
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'Account identity mapping is immutable.');
END;
/

CREATE INDEX IDX_MAIMEI_ACCOUNTS_ROLE_CODE
    ON MAIMEI_ACCOUNTS (ROLE_CODE);

CREATE INDEX IDX_MAIMEI_ACCOUNTS_STATUS_CODE
    ON MAIMEI_ACCOUNTS (STATUS_CODE);
