-- MAIMEI 講師テーブル
CREATE TABLE MAIMEI_TEACHERS (
    TEACHER_ID NUMBER(19, 0) NOT NULL,
    TEACHER_CODE VARCHAR2(12 CHAR) NOT NULL,
    ACADEMY_CODE VARCHAR2(12 CHAR),
    LOGIN_ID VARCHAR2(100 CHAR) NOT NULL,
    PASSWORD_HASH VARCHAR2(255 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(100 CHAR) NOT NULL,
    EMAIL VARCHAR2(255 CHAR),
    PHONE VARCHAR2(30 CHAR) NOT NULL,
    PRESET CLOB,
    AVAILABLE_SCHEDULE CLOB,
    NOTE_BODY CLOB,
    STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    LAST_LOGIN_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    DELETED_AT TIMESTAMP(6),
    CONSTRAINT PK_MAIMEI_TEACHERS PRIMARY KEY (TEACHER_ID),
    CONSTRAINT UQ_MAIMEI_TEACHERS_CODE UNIQUE (TEACHER_CODE),
    CONSTRAINT UQ_MAIMEI_TEACHERS_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UQ_MAIMEI_TEACHERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_MAIMEI_TEACHERS_ACADEMY_CODE FOREIGN KEY (ACADEMY_CODE)
        REFERENCES MAIMEI_ACADEMIES (ACADEMY_CODE),
    CONSTRAINT CK_MAIMEI_TEACHERS_STATUS_CODE CHECK (STATUS_CODE IN ('PENDING', 'ACTIVE', 'INACTIVE', 'HOLD')),
    CONSTRAINT CK_MAIMEI_TEACHERS_PENDING_ACADEMY CHECK (
        (STATUS_CODE = 'PENDING' AND ACADEMY_CODE IS NULL)
        OR (STATUS_CODE IN ('ACTIVE', 'INACTIVE', 'HOLD') AND ACADEMY_CODE IS NOT NULL)
    )
);

COMMENT ON COLUMN MAIMEI_TEACHERS.TEACHER_ID IS '講師の数値ベース内部主キー';
COMMENT ON COLUMN MAIMEI_TEACHERS.TEACHER_CODE IS '講師を外部から識別する不変コード';
COMMENT ON COLUMN MAIMEI_TEACHERS.ACADEMY_CODE IS '所属塾コード。承認前はNULL許可';
COMMENT ON COLUMN MAIMEI_TEACHERS.LOGIN_ID IS 'ログインに使用する一意ID';
COMMENT ON COLUMN MAIMEI_TEACHERS.PASSWORD_HASH IS 'パスワードハッシュ値';
COMMENT ON COLUMN MAIMEI_TEACHERS.DISPLAY_NAME IS '講師表示名';
COMMENT ON COLUMN MAIMEI_TEACHERS.EMAIL IS '講師メールアドレス';
COMMENT ON COLUMN MAIMEI_TEACHERS.PHONE IS '講師携帯電話番号';
COMMENT ON COLUMN MAIMEI_TEACHERS.PRESET IS '講師用PRESET JSON。形式例: { "version": 2, "presets": [{ "id": "1", "name": "Soft Daily Coral", "createdAt": "2026-04-02T09:00:00+09:00", "updatedAt": "2026-04-02T09:00:00+09:00", "note": "Daily coral tone preset for soft warm classes.", "items": { "base_foundation": [{ "source": "inventory", "sku": "FND-001", "itemName": "Soft Natural Foundation 01", "imageUrl": "https://example.com/images/fnd-001.jpg" }], "blush": [{ "source": "inventory", "sku": "BLS-002", "itemName": "Soft Peach Blush", "imageUrl": "https://example.com/images/bls-002.jpg" }], "lip_color": [{ "source": "inventory", "sku": "LIP-014", "itemName": "Muted Coral Lip", "imageUrl": "https://example.com/images/lip-014.jpg" }], "eyeshadow": null, "contour": null, "highlighter": null, "etc": null } }] }';
COMMENT ON COLUMN MAIMEI_TEACHERS.AVAILABLE_SCHEDULE IS '旧講師予約可能時間JSON。新規保存先は MAIMEI_TEACHER_AVAILABLE_SCHEDULES を使用する';
COMMENT ON COLUMN MAIMEI_TEACHERS.NOTE_BODY IS '講師に関する自由記述メモ';
COMMENT ON COLUMN MAIMEI_TEACHERS.STATUS_CODE IS '講師状態コード';
COMMENT ON COLUMN MAIMEI_TEACHERS.LAST_LOGIN_AT IS '最終ログイン日時';
COMMENT ON COLUMN MAIMEI_TEACHERS.CREATED_AT IS '初回作成日時';
COMMENT ON COLUMN MAIMEI_TEACHERS.CREATED_BY IS '初回作成者';
COMMENT ON COLUMN MAIMEI_TEACHERS.UPDATED_AT IS '最終更新日時';
COMMENT ON COLUMN MAIMEI_TEACHERS.UPDATED_BY IS '最終更新者';
COMMENT ON COLUMN MAIMEI_TEACHERS.DELETED_AT IS '論理削除日時';

CREATE SEQUENCE MAIMEI_TEACHERS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE MAIMEI_TEACHER_CODE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER MAIMEI_TEACHERS_BIR
BEFORE INSERT ON MAIMEI_TEACHERS
FOR EACH ROW
BEGIN
    IF :NEW.TEACHER_ID IS NULL THEN
        SELECT MAIMEI_TEACHERS_SEQ.NEXTVAL
          INTO :NEW.TEACHER_ID
          FROM DUAL;
    END IF;

    IF :NEW.TEACHER_CODE IS NULL THEN
        SELECT 'TC' || LPAD(MAIMEI_TEACHER_CODE_SEQ.NEXTVAL, 10, '0')
          INTO :NEW.TEACHER_CODE
          FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_TEACHERS_BUR
BEFORE UPDATE ON MAIMEI_TEACHERS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_TEACHERS_BUC
BEFORE UPDATE OF TEACHER_CODE ON MAIMEI_TEACHERS
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'TEACHER_CODE is immutable.');
END;
/

CREATE INDEX IDX_MAIMEI_TEACHERS_ACADEMY_CODE
    ON MAIMEI_TEACHERS (ACADEMY_CODE);

CREATE INDEX IDX_MAIMEI_TEACHERS_STATUS_CODE
    ON MAIMEI_TEACHERS (STATUS_CODE);
