-- MAIMEI 講師予約可能時間テーブル
CREATE TABLE MAIMEI_TEACHER_AVAILABLE_SCHEDULES (
    TEACHER_ID NUMBER(19, 0) NOT NULL,
    TIMEZONE VARCHAR2(100 CHAR) DEFAULT 'Asia/Seoul' NOT NULL,
    SCHEDULE_BODY CLOB,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    CONSTRAINT PK_MAIMEI_TEACHER_AVAILABLE_SCHEDULES PRIMARY KEY (TEACHER_ID),
    CONSTRAINT FK_MAIMEI_TEACHER_AVAILABLE_SCHEDULES_TEACHER_ID FOREIGN KEY (TEACHER_ID)
        REFERENCES MAIMEI_TEACHERS (TEACHER_ID)
);

COMMENT ON COLUMN MAIMEI_TEACHER_AVAILABLE_SCHEDULES.TEACHER_ID IS '講師内部主キー。講師ごとに1件のscheduleを保持する';
COMMENT ON COLUMN MAIMEI_TEACHER_AVAILABLE_SCHEDULES.TIMEZONE IS 'schedule評価に使うIANA timezone';
COMMENT ON COLUMN MAIMEI_TEACHER_AVAILABLE_SCHEDULES.SCHEDULE_BODY IS '講師予約可能時間JSON。形式例: { "timezone": "Asia/Seoul", "weekly": { "mon": [{ "start": "10:00", "end": "12:00" }], "tue": [], "wed": [], "thu": [], "fri": [], "sat": [], "sun": [] }, "exceptions": [{ "date": "2026-04-01", "closed": true }] }';
COMMENT ON COLUMN MAIMEI_TEACHER_AVAILABLE_SCHEDULES.CREATED_AT IS '初回作成日時';
COMMENT ON COLUMN MAIMEI_TEACHER_AVAILABLE_SCHEDULES.CREATED_BY IS '初回作成者';
COMMENT ON COLUMN MAIMEI_TEACHER_AVAILABLE_SCHEDULES.UPDATED_AT IS '最終更新日時';
COMMENT ON COLUMN MAIMEI_TEACHER_AVAILABLE_SCHEDULES.UPDATED_BY IS '最終更新者';

CREATE OR REPLACE TRIGGER MAIMEI_TEACHER_AVAILABLE_SCHEDULES_BUR
BEFORE UPDATE ON MAIMEI_TEACHER_AVAILABLE_SCHEDULES
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE INDEX IDX_MAIMEI_TEACHER_AVAILABLE_SCHEDULES_UPDATED_AT
    ON MAIMEI_TEACHER_AVAILABLE_SCHEDULES (UPDATED_AT);

INSERT INTO MAIMEI_TEACHER_AVAILABLE_SCHEDULES (
    TEACHER_ID,
    TIMEZONE,
    SCHEDULE_BODY
)
SELECT
    tch.TEACHER_ID,
    NVL(JSON_VALUE(tch.AVAILABLE_SCHEDULE, '$.timezone'), 'Asia/Seoul'),
    tch.AVAILABLE_SCHEDULE
FROM MAIMEI_TEACHERS tch
WHERE tch.AVAILABLE_SCHEDULE IS NOT NULL;
