-- MAIMEI 管理者テーブル
CREATE TABLE MAIMEI_ADMINS (
    ADMIN_ID NUMBER(19, 0) NOT NULL,
    ADMIN_CODE VARCHAR2(12 CHAR) NOT NULL,
    ACADEMY_CODE VARCHAR2(12 CHAR),
    LOGIN_ID VARCHAR2(100 CHAR) NOT NULL,
    PASSWORD_HASH VARCHAR2(255 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(100 CHAR) NOT NULL,
    EMAIL VARCHAR2(255 CHAR),
    PHONE VARCHAR2(30 CHAR) NOT NULL,
    NOTE_BODY CLOB,
    AUTH_POLICY CLOB,
    ROLE_CODE VARCHAR2(30 CHAR) NOT NULL,
    STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    LAST_LOGIN_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    DELETED_AT TIMESTAMP(6),
    CONSTRAINT PK_MAIMEI_ADMINS PRIMARY KEY (ADMIN_ID),
    CONSTRAINT UQ_MAIMEI_ADMINS_CODE UNIQUE (ADMIN_CODE),
    CONSTRAINT UQ_MAIMEI_ADMINS_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UQ_MAIMEI_ADMINS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_MAIMEI_ADMINS_ACADEMY_CODE FOREIGN KEY (ACADEMY_CODE)
        REFERENCES MAIMEI_ACADEMIES (ACADEMY_CODE),
    CONSTRAINT CK_MAIMEI_ADMINS_ROLE_CODE CHECK (ROLE_CODE IN ('ROOT', 'ADMIN')),
    CONSTRAINT CK_MAIMEI_ADMINS_STATUS_CODE CHECK (STATUS_CODE IN ('PENDING', 'ACTIVE', 'INACTIVE', 'HOLD')),
    CONSTRAINT CK_MAIMEI_ADMINS_PENDING_ACADEMY CHECK (
        (ROLE_CODE = 'ROOT' AND STATUS_CODE IN ('ACTIVE', 'INACTIVE', 'HOLD') AND ACADEMY_CODE IS NOT NULL)
        OR (ROLE_CODE = 'ADMIN' AND STATUS_CODE = 'PENDING' AND ACADEMY_CODE IS NULL)
        OR (ROLE_CODE = 'ADMIN' AND STATUS_CODE IN ('ACTIVE', 'INACTIVE', 'HOLD') AND ACADEMY_CODE IS NOT NULL)
    )
);

COMMENT ON COLUMN MAIMEI_ADMINS.ADMIN_ID IS '管理者の数値ベース内部主キー';
COMMENT ON COLUMN MAIMEI_ADMINS.ADMIN_CODE IS '管理者を外部から識別する不変コード';
COMMENT ON COLUMN MAIMEI_ADMINS.ACADEMY_CODE IS '所属学院コード。承認前のADMINはNULL許容';
COMMENT ON COLUMN MAIMEI_ADMINS.LOGIN_ID IS 'ログインに使用する一意ID';
COMMENT ON COLUMN MAIMEI_ADMINS.PASSWORD_HASH IS 'パスワードハッシュ値';
COMMENT ON COLUMN MAIMEI_ADMINS.DISPLAY_NAME IS '管理者表示名';
COMMENT ON COLUMN MAIMEI_ADMINS.EMAIL IS '管理者メールアドレス';
COMMENT ON COLUMN MAIMEI_ADMINS.PHONE IS '管理者携帯電話番号';
COMMENT ON COLUMN MAIMEI_ADMINS.NOTE_BODY IS '管理者に関する自由メモ';
COMMENT ON COLUMN MAIMEI_ADMINS.AUTH_POLICY IS 'AWS IAM類似のJSON権限文書';
COMMENT ON COLUMN MAIMEI_ADMINS.ROLE_CODE IS '管理者権限コード(ROOTまたはADMIN)';
COMMENT ON COLUMN MAIMEI_ADMINS.STATUS_CODE IS '管理者状態コード';
COMMENT ON COLUMN MAIMEI_ADMINS.LAST_LOGIN_AT IS '最終ログイン日時';
COMMENT ON COLUMN MAIMEI_ADMINS.CREATED_AT IS '初回作成日時';
COMMENT ON COLUMN MAIMEI_ADMINS.CREATED_BY IS '初回作成者';
COMMENT ON COLUMN MAIMEI_ADMINS.UPDATED_AT IS '最終更新日時';
COMMENT ON COLUMN MAIMEI_ADMINS.UPDATED_BY IS '最終更新者';
COMMENT ON COLUMN MAIMEI_ADMINS.DELETED_AT IS '論理削除日時';

CREATE SEQUENCE MAIMEI_ADMINS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE MAIMEI_ADMIN_CODE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER MAIMEI_ADMINS_BIR
BEFORE INSERT ON MAIMEI_ADMINS
FOR EACH ROW
BEGIN
    IF :NEW.ADMIN_ID IS NULL THEN
        SELECT MAIMEI_ADMINS_SEQ.NEXTVAL
          INTO :NEW.ADMIN_ID
          FROM DUAL;
    END IF;

    IF :NEW.ADMIN_CODE IS NULL THEN
        SELECT 'AD' || LPAD(MAIMEI_ADMIN_CODE_SEQ.NEXTVAL, 10, '0')
          INTO :NEW.ADMIN_CODE
          FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_ADMINS_BUR
BEFORE UPDATE ON MAIMEI_ADMINS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_ADMINS_BUC
BEFORE UPDATE OF ADMIN_CODE ON MAIMEI_ADMINS
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'ADMIN_CODE is immutable.');
END;
/

CREATE UNIQUE INDEX UQ_MAIMEI_ADMINS_ROOT_PER_ACADEMY
    ON MAIMEI_ADMINS (
        CASE
            WHEN ROLE_CODE = 'ROOT' THEN ACADEMY_CODE
        END
    );

CREATE INDEX IDX_MAIMEI_ADMINS_ACADEMY_CODE
    ON MAIMEI_ADMINS (ACADEMY_CODE);

CREATE INDEX IDX_MAIMEI_ADMINS_ROLE_CODE
    ON MAIMEI_ADMINS (ROLE_CODE);

CREATE INDEX IDX_MAIMEI_ADMINS_STATUS_CODE
    ON MAIMEI_ADMINS (STATUS_CODE);

