CREATE TABLE MAIMEI_LESSON_RESERVATIONS (
    RESERVATION_ID NUMBER(19, 0) NOT NULL,
    RESERVATION_CODE VARCHAR2(12 CHAR) NOT NULL,
    ACADEMY_CODE VARCHAR2(12 CHAR) NOT NULL,
    STUDENT_ID NUMBER(19, 0) NOT NULL,
    TEACHER_ID NUMBER(19, 0) NOT NULL,
    PRESET_ID VARCHAR2(200 CHAR),
    STARTS_AT_UTC TIMESTAMP(6) NOT NULL,
    RESERVATION_AT TIMESTAMP(6) NOT NULL,
    STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'PENDING' NOT NULL,
    CANCELED_AT TIMESTAMP(6),
    NOTE_BODY CLOB,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    CONSTRAINT PK_MAIMEI_LESSON_RESERVATIONS PRIMARY KEY (RESERVATION_ID),
    CONSTRAINT UQ_MAIMEI_LESSON_RESERVATIONS_CODE UNIQUE (RESERVATION_CODE),
    CONSTRAINT FK_MAIMEI_LESSON_RESERVATIONS_ACADEMY_CODE FOREIGN KEY (ACADEMY_CODE)
        REFERENCES MAIMEI_ACADEMIES (ACADEMY_CODE),
    CONSTRAINT FK_MAIMEI_LESSON_RESERVATIONS_STUDENT_ID FOREIGN KEY (STUDENT_ID)
        REFERENCES MAIMEI_STUDENTS (STUDENT_ID),
    CONSTRAINT FK_MAIMEI_LESSON_RESERVATIONS_TEACHER_ID FOREIGN KEY (TEACHER_ID)
        REFERENCES MAIMEI_TEACHERS (TEACHER_ID),
    CONSTRAINT CK_MAIMEI_LESSON_RESERVATIONS_STATUS_CODE CHECK (
        STATUS_CODE IN ('PENDING', 'CONFIRMED', 'CANCELED')
    )
);

COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.RESERVATION_ID IS '予約の数値ベース内部主キー';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.RESERVATION_CODE IS '予約を外部から識別する不変コード';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.ACADEMY_CODE IS '予約が属する塾コード';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.STUDENT_ID IS '予約した学生ID';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.TEACHER_ID IS '予約対象の講師ID';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.PRESET_ID IS '予約時に使用する講師preset識別子';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.STARTS_AT_UTC IS '予約開始UTC基準時刻';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.RESERVATION_AT IS '予約基準ローカル開始日時';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.STATUS_CODE IS '予約状態コード';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.CANCELED_AT IS 'キャンセル日時';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.NOTE_BODY IS '予約メモ本文';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.CREATED_AT IS '初回作成日時';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.CREATED_BY IS '初回作成者';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.UPDATED_AT IS '最終更新日時';
COMMENT ON COLUMN MAIMEI_LESSON_RESERVATIONS.UPDATED_BY IS '最終更新者';

CREATE SEQUENCE MAIMEI_LESSON_RESERVATIONS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE MAIMEI_RESERVATION_CODE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER MAIMEI_LESSON_RESERVATIONS_BIR
BEFORE INSERT ON MAIMEI_LESSON_RESERVATIONS
FOR EACH ROW
BEGIN
    IF :NEW.RESERVATION_ID IS NULL THEN
        SELECT MAIMEI_LESSON_RESERVATIONS_SEQ.NEXTVAL
          INTO :NEW.RESERVATION_ID
          FROM DUAL;
    END IF;

    IF :NEW.RESERVATION_CODE IS NULL THEN
        SELECT 'RV' || LPAD(MAIMEI_RESERVATION_CODE_SEQ.NEXTVAL, 10, '0')
          INTO :NEW.RESERVATION_CODE
          FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_LESSON_RESERVATIONS_BUR
BEFORE UPDATE ON MAIMEI_LESSON_RESERVATIONS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_LESSON_RESERVATIONS_BUC
BEFORE UPDATE OF RESERVATION_CODE ON MAIMEI_LESSON_RESERVATIONS
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'RESERVATION_CODE is immutable.');
END;
/

CREATE INDEX IDX_MAIMEI_LESSON_RESERVATIONS_STUDENT_DATE
    ON MAIMEI_LESSON_RESERVATIONS (STUDENT_ID, RESERVATION_AT);

CREATE INDEX IDX_MAIMEI_LESSON_RESERVATIONS_TEACHER_DATE
    ON MAIMEI_LESSON_RESERVATIONS (TEACHER_ID, RESERVATION_AT);

CREATE INDEX IDX_MAIMEI_LESSON_RESERVATIONS_STATUS
    ON MAIMEI_LESSON_RESERVATIONS (STATUS_CODE);

CREATE INDEX IDX_MAIMEI_LESSON_RESERVATIONS_STARTS_AT_UTC
    ON MAIMEI_LESSON_RESERVATIONS (STARTS_AT_UTC);

CREATE INDEX IDX_MAIMEI_LESSON_RESERVATIONS_PRESET_ID
    ON MAIMEI_LESSON_RESERVATIONS (PRESET_ID);

CREATE UNIQUE INDEX UQ_MAIMEI_LESSON_RESERVATIONS_ACTIVE_SLOT
    ON MAIMEI_LESSON_RESERVATIONS (
        CASE WHEN STATUS_CODE IN ('PENDING', 'CONFIRMED') THEN TEACHER_ID END,
        CASE WHEN STATUS_CODE IN ('PENDING', 'CONFIRMED') THEN STARTS_AT_UTC END
    );
