-- MAIMEI スタッフテーブル
CREATE TABLE MAIMEI_STAFF (
    STAFF_ID NUMBER(19, 0) NOT NULL,
    STAFF_CODE VARCHAR2(12 CHAR) NOT NULL,
    ACADEMY_CODE VARCHAR2(12 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(100 CHAR) NOT NULL,
    EMAIL VARCHAR2(255 CHAR),
    PHONE VARCHAR2(30 CHAR) NOT NULL,
    NOTE_BODY CLOB,
    AUTH_POLICY CLOB,
    ROLE_CODE VARCHAR2(30 CHAR) NOT NULL,
    STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    DELETED_AT TIMESTAMP(6),
    CONSTRAINT PK_MAIMEI_STAFF PRIMARY KEY (STAFF_ID),
    CONSTRAINT UQ_MAIMEI_STAFF_CODE UNIQUE (STAFF_CODE),
    CONSTRAINT UQ_MAIMEI_STAFF_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_MAIMEI_STAFF_ACADEMY_CODE FOREIGN KEY (ACADEMY_CODE)
        REFERENCES MAIMEI_ACADEMIES (ACADEMY_CODE),
    CONSTRAINT CK_MAIMEI_STAFF_ROLE_CODE CHECK (ROLE_CODE IN ('ROOT', 'ADMIN')),
    CONSTRAINT CK_MAIMEI_STAFF_STATUS_CODE CHECK (STATUS_CODE IN ('ACTIVE', 'INACTIVE', 'HOLD'))
);

COMMENT ON COLUMN MAIMEI_STAFF.STAFF_ID IS 'スタッフの数値ベース内部主キー';
COMMENT ON COLUMN MAIMEI_STAFF.STAFF_CODE IS 'スタッフを外部から識別する不変コード';
COMMENT ON COLUMN MAIMEI_STAFF.ACADEMY_CODE IS '所属塾コード';
COMMENT ON COLUMN MAIMEI_STAFF.DISPLAY_NAME IS 'スタッフ表示名';
COMMENT ON COLUMN MAIMEI_STAFF.EMAIL IS 'スタッフメールアドレス';
COMMENT ON COLUMN MAIMEI_STAFF.PHONE IS 'スタッフ携帯電話番号';
COMMENT ON COLUMN MAIMEI_STAFF.NOTE_BODY IS 'スタッフに関する自由記述メモ';
COMMENT ON COLUMN MAIMEI_STAFF.AUTH_POLICY IS 'AWS IAM類似JSON権限文書。形式例: { "version": "2026-03-27", "statements": [{ "effect": "allow", "actions": ["student.read"], "resources": ["academy:self/student/*"] }] }';
COMMENT ON COLUMN MAIMEI_STAFF.ROLE_CODE IS 'スタッフ権限コード(ROOTまたはADMIN)';
COMMENT ON COLUMN MAIMEI_STAFF.STATUS_CODE IS 'スタッフ状態コード';
COMMENT ON COLUMN MAIMEI_STAFF.CREATED_AT IS '初回作成日時';
COMMENT ON COLUMN MAIMEI_STAFF.CREATED_BY IS '初回作成者';
COMMENT ON COLUMN MAIMEI_STAFF.UPDATED_AT IS '最終更新日時';
COMMENT ON COLUMN MAIMEI_STAFF.UPDATED_BY IS '最終更新者';
COMMENT ON COLUMN MAIMEI_STAFF.DELETED_AT IS '論理削除日時';

CREATE SEQUENCE MAIMEI_STAFF_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE MAIMEI_STAFF_CODE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER MAIMEI_STAFF_BIR
BEFORE INSERT ON MAIMEI_STAFF
FOR EACH ROW
BEGIN
    IF :NEW.STAFF_ID IS NULL THEN
        SELECT MAIMEI_STAFF_SEQ.NEXTVAL
          INTO :NEW.STAFF_ID
          FROM DUAL;
    END IF;

    IF :NEW.STAFF_CODE IS NULL THEN
        SELECT 'SF' || LPAD(MAIMEI_STAFF_CODE_SEQ.NEXTVAL, 10, '0')
          INTO :NEW.STAFF_CODE
          FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_STAFF_BUR
BEFORE UPDATE ON MAIMEI_STAFF
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_STAFF_BUC
BEFORE UPDATE OF STAFF_CODE ON MAIMEI_STAFF
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'STAFF_CODE is immutable.');
END;
/

CREATE UNIQUE INDEX UQ_MAIMEI_STAFF_ROOT_PER_ACADEMY
    ON MAIMEI_STAFF (
        CASE
            WHEN ROLE_CODE = 'ROOT' THEN ACADEMY_CODE
        END
    );

CREATE INDEX IDX_MAIMEI_STAFF_ACADEMY_CODE
    ON MAIMEI_STAFF (ACADEMY_CODE);

CREATE INDEX IDX_MAIMEI_STAFF_ROLE_CODE
    ON MAIMEI_STAFF (ROLE_CODE);
