-- MAIMEI ライセンステーブル
CREATE TABLE MAIMEI_LICENSES (
    LICENSE_ID NUMBER(19, 0) NOT NULL,
    LICENSE_CODE VARCHAR2(32 CHAR) NOT NULL,
    ACADEMY_CODE VARCHAR2(12 CHAR),
    STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'UNASSIGNED' NOT NULL,
    EXPIRES_AT TIMESTAMP(6) NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    CONSTRAINT PK_MAIMEI_LICENSES PRIMARY KEY (LICENSE_ID),
    CONSTRAINT UQ_MAIMEI_LICENSES_CODE UNIQUE (LICENSE_CODE),
    CONSTRAINT FK_MAIMEI_LICENSES_ACADEMY_CODE FOREIGN KEY (ACADEMY_CODE)
        REFERENCES MAIMEI_ACADEMIES (ACADEMY_CODE),
    CONSTRAINT CK_MAIMEI_LICENSES_STATUS_CODE CHECK (
        STATUS_CODE IN ('UNASSIGNED', 'ACTIVE', 'EXPIRED', 'SUSPENDED')
    )
);

COMMENT ON COLUMN MAIMEI_LICENSES.LICENSE_ID IS 'ライセンスの数値ベース内部主キー';
COMMENT ON COLUMN MAIMEI_LICENSES.LICENSE_CODE IS 'ライセンスを外部から識別する不変コード';
COMMENT ON COLUMN MAIMEI_LICENSES.ACADEMY_CODE IS 'ライセンスが割り当てられた塾コード';
COMMENT ON COLUMN MAIMEI_LICENSES.STATUS_CODE IS 'ライセンス状態コード';
COMMENT ON COLUMN MAIMEI_LICENSES.EXPIRES_AT IS 'ライセンス有効期限';
COMMENT ON COLUMN MAIMEI_LICENSES.CREATED_AT IS '初回作成日時';
COMMENT ON COLUMN MAIMEI_LICENSES.CREATED_BY IS '初回作成者';
COMMENT ON COLUMN MAIMEI_LICENSES.UPDATED_AT IS '最終更新日時';
COMMENT ON COLUMN MAIMEI_LICENSES.UPDATED_BY IS '最終更新者';

-- 数値ベースのライセンス内部主キー採番用シーケンス
CREATE SEQUENCE MAIMEI_LICENSES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- INSERT 時に主キーと監査日時の初期値を補完するトリガー
CREATE OR REPLACE TRIGGER MAIMEI_LICENSES_BIR
BEFORE INSERT ON MAIMEI_LICENSES
FOR EACH ROW
BEGIN
    IF :NEW.LICENSE_ID IS NULL THEN
        SELECT MAIMEI_LICENSES_SEQ.NEXTVAL
          INTO :NEW.LICENSE_ID
          FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

-- UPDATE 時に更新日時を自動更新するトリガー
CREATE OR REPLACE TRIGGER MAIMEI_LICENSES_BUR
BEFORE UPDATE ON MAIMEI_LICENSES
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- 一度ひも付けた塾コードは別の塾へ変更できないようにするトリガー
CREATE OR REPLACE TRIGGER MAIMEI_LICENSES_BUA
BEFORE UPDATE OF ACADEMY_CODE ON MAIMEI_LICENSES
FOR EACH ROW
BEGIN
    IF :OLD.ACADEMY_CODE IS NOT NULL
       AND NVL(:NEW.ACADEMY_CODE, '__NULL__') <> :OLD.ACADEMY_CODE THEN
        RAISE_APPLICATION_ERROR(-20002, 'ACADEMY_CODE cannot be changed once assigned.');
    END IF;
END;
/

-- ライセンスステータス検索用インデックス
CREATE INDEX IDX_MAIMEI_LICENSES_STATUS_CODE
    ON MAIMEI_LICENSES (STATUS_CODE);

-- 塾コード検索用インデックス
CREATE INDEX IDX_MAIMEI_LICENSES_ACADEMY_CODE
    ON MAIMEI_LICENSES (ACADEMY_CODE);
