-- MAIMEI 在庫品目テーブル
CREATE TABLE MAIMEI_INVENTORIES (
    ITEM_ID NUMBER(19, 0) NOT NULL,
    ITEM_CODE VARCHAR2(12 CHAR) NOT NULL,
    ACADEMY_CODE VARCHAR2(12 CHAR) NOT NULL,
    SKU VARCHAR2(100 CHAR) NOT NULL,
    ITEM_NAME VARCHAR2(200 CHAR) NOT NULL,
    CATEGORY_CODE VARCHAR2(50 CHAR) NOT NULL,
    COST NUMBER(12, 2) NOT NULL,
    PRICE NUMBER(12, 2) NOT NULL,
    L_VALUE NUMBER(10, 4) NOT NULL,
    C_VALUE NUMBER(10, 4) NOT NULL,
    H_VALUE NUMBER(10, 4) NOT NULL,
    IMAGE_URL VARCHAR2(500 CHAR),
    STOCK_COUNT NUMBER(10, 0) DEFAULT 0 NOT NULL,
    NOTE_BODY CLOB,
    STATUS_CODE VARCHAR2(30 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(100 CHAR),
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100 CHAR),
    DELETED_AT TIMESTAMP(6),
    CONSTRAINT PK_MAIMEI_INVENTORIES PRIMARY KEY (ITEM_ID),
    CONSTRAINT UQ_MAIMEI_INVENTORIES_CODE UNIQUE (ITEM_CODE),
    CONSTRAINT UQ_MAIMEI_INVENTORIES_SKU UNIQUE (SKU),
    CONSTRAINT FK_MAIMEI_INVENTORIES_ACADEMY_CODE FOREIGN KEY (ACADEMY_CODE)
        REFERENCES MAIMEI_ACADEMIES (ACADEMY_CODE),
    CONSTRAINT CK_MAIMEI_INVENTORIES_CATEGORY_CODE CHECK (CATEGORY_CODE IN (
        'base_foundation',
        'blush',
        'lip_color',
        'eyeshadow',
        'contour',
        'highlighter',
        'etc'
    )),
    CONSTRAINT CK_MAIMEI_INVENTORIES_STATUS_CODE CHECK (STATUS_CODE IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT CK_MAIMEI_INVENTORIES_COST CHECK (COST >= 0),
    CONSTRAINT CK_MAIMEI_INVENTORIES_PRICE CHECK (PRICE >= 0),
    CONSTRAINT CK_MAIMEI_INVENTORIES_L_VALUE CHECK (L_VALUE >= 0 AND L_VALUE <= 100),
    CONSTRAINT CK_MAIMEI_INVENTORIES_C_VALUE CHECK (C_VALUE >= 0),
    CONSTRAINT CK_MAIMEI_INVENTORIES_H_VALUE CHECK (H_VALUE >= 0 AND H_VALUE < 360),
    CONSTRAINT CK_MAIMEI_INVENTORIES_STOCK CHECK (STOCK_COUNT >= 0)
);

COMMENT ON COLUMN MAIMEI_INVENTORIES.ITEM_ID IS '在庫品目の数値ベース内部主キー';
COMMENT ON COLUMN MAIMEI_INVENTORIES.ITEM_CODE IS '在庫品目を外部から識別する不変コード';
COMMENT ON COLUMN MAIMEI_INVENTORIES.ACADEMY_CODE IS '所属塾コード';
COMMENT ON COLUMN MAIMEI_INVENTORIES.SKU IS '在庫管理番号';
COMMENT ON COLUMN MAIMEI_INVENTORIES.ITEM_NAME IS '品目名';
COMMENT ON COLUMN MAIMEI_INVENTORIES.CATEGORY_CODE IS '品目カテゴリーコード';
COMMENT ON COLUMN MAIMEI_INVENTORIES.COST IS '品目原価';
COMMENT ON COLUMN MAIMEI_INVENTORIES.PRICE IS '品目販売価格';
COMMENT ON COLUMN MAIMEI_INVENTORIES.L_VALUE IS '品目代表色のL値';
COMMENT ON COLUMN MAIMEI_INVENTORIES.C_VALUE IS '品目代表色のC値';
COMMENT ON COLUMN MAIMEI_INVENTORIES.H_VALUE IS '品目代表色のH値';
COMMENT ON COLUMN MAIMEI_INVENTORIES.IMAGE_URL IS '品目画像URL';
COMMENT ON COLUMN MAIMEI_INVENTORIES.STOCK_COUNT IS '現在の在庫数';
COMMENT ON COLUMN MAIMEI_INVENTORIES.NOTE_BODY IS '品目に関する自由記述メモ';
COMMENT ON COLUMN MAIMEI_INVENTORIES.STATUS_CODE IS '品目状態コード';
COMMENT ON COLUMN MAIMEI_INVENTORIES.CREATED_AT IS '初回作成日時';
COMMENT ON COLUMN MAIMEI_INVENTORIES.CREATED_BY IS '初回作成者';
COMMENT ON COLUMN MAIMEI_INVENTORIES.UPDATED_AT IS '最終更新日時';
COMMENT ON COLUMN MAIMEI_INVENTORIES.UPDATED_BY IS '最終更新者';
COMMENT ON COLUMN MAIMEI_INVENTORIES.DELETED_AT IS '論理削除日時';

CREATE SEQUENCE MAIMEI_INVENTORIES_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE MAIMEI_INVENTORY_CODE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER MAIMEI_INVENTORIES_BIR
BEFORE INSERT ON MAIMEI_INVENTORIES
FOR EACH ROW
BEGIN
    IF :NEW.ITEM_ID IS NULL THEN
        SELECT MAIMEI_INVENTORIES_SEQ.NEXTVAL
          INTO :NEW.ITEM_ID
          FROM DUAL;
    END IF;

    IF :NEW.ITEM_CODE IS NULL THEN
        SELECT 'IV' || LPAD(MAIMEI_INVENTORY_CODE_SEQ.NEXTVAL, 10, '0')
          INTO :NEW.ITEM_CODE
          FROM DUAL;
    END IF;

    IF :NEW.CREATED_AT IS NULL THEN
        :NEW.CREATED_AT := SYSTIMESTAMP;
    END IF;

    IF :NEW.UPDATED_AT IS NULL THEN
        :NEW.UPDATED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_INVENTORIES_BUR
BEFORE UPDATE ON MAIMEI_INVENTORIES
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER MAIMEI_INVENTORIES_BUC
BEFORE UPDATE OF ITEM_CODE ON MAIMEI_INVENTORIES
FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'ITEM_CODE is immutable.');
END;
/

CREATE INDEX IDX_MAIMEI_INVENTORIES_ACADEMY_CODE
    ON MAIMEI_INVENTORIES (ACADEMY_CODE);

CREATE INDEX IDX_MAIMEI_INVENTORIES_CATEGORY_CODE
    ON MAIMEI_INVENTORIES (CATEGORY_CODE);

CREATE INDEX IDX_MAIMEI_INVENTORIES_STATUS_CODE
    ON MAIMEI_INVENTORIES (STATUS_CODE);
