ALTER TABLE MAIMEI_INVENTORIES
    ADD (
        BARCODE VARCHAR2(100 CHAR),
        REORDER_LEVEL NUMBER(10, 0) DEFAULT 0 NOT NULL,
        SUPPLIER VARCHAR2(200 CHAR),
        LOCATION VARCHAR2(100 CHAR)
    );

ALTER TABLE MAIMEI_INVENTORIES
    ADD CONSTRAINT CK_MAIMEI_INVENTORIES_REORDER_LEVEL CHECK (REORDER_LEVEL >= 0);

COMMENT ON COLUMN MAIMEI_INVENTORIES.BARCODE IS '品目バーコード';
COMMENT ON COLUMN MAIMEI_INVENTORIES.REORDER_LEVEL IS '再発注基準数';
COMMENT ON COLUMN MAIMEI_INVENTORIES.SUPPLIER IS '仕入先名';
COMMENT ON COLUMN MAIMEI_INVENTORIES.LOCATION IS '保管場所';
