import type {LanguageMode} from '../../../shared/shell-model';

export const DESKTOP_SHELL_LABELS = {
  ja: {
    academyCode: '学園コード',
    academyName: '学園名',
    account: 'アカウント',
    allChecks: '全ヘルスチェック実行',
    allChecksHint: 'ローカル、Docker、クラウドの順で確認します。',
    cloud: 'クラウドサーバー',
    devHealth: '開発者オプション',
    devHealthBody:
      '現在のデスクトップクライアントから各サーバー接続を確認します。',
    devLicenseCreate: 'ライセンス生成',
    devLicenseCreateHint: '未割り当てライセンスを 1 件発行します。',
    devResult: '開発者アクション結果',
    devTableInit: 'テーブル初期化',
    devTableInitHint: '管理対象テーブルを再作成し、マイグレーションを順に適用します。',
    dark: 'ダーク',
    docker: 'Dockerサーバー',
    env: '環境',
    general: '一般設定',
    confirmPassword: 'パスワード確認',
    createAccount: 'アカウント作成',
    copyLicenseCode: 'ライセンスコードをコピー',
    displayName: '表示名',
    guestHint: '登録したアカウントでログインするとプロフィールと保護コントロールを確認できます。',
    invalid: 'アカウントIDまたはパスワードが正しくありません。',
    accountInactive: 'このアカウントは無効です。',
    accountOnHold: 'このアカウントは現在保留中です。',
    accountPending: 'このアカウントは承認待ちです。',
    academyInactive: '所属学園は現在利用できません。',
    academyCreateFailed: '学園を作成できませんでした。しばらくしてからもう一度お試しください。',
    duplicateLoginId: 'このログインIDは既に使用されています。別のIDを入力してください。',
    language: '言語',
    lastChecked: '最終確認',
    light: 'ライト',
    local: 'ローカルサーバー',
    locked: '保護設定は現在ロックされています。',
    loginNotice: 'ログイン案内',
    login: 'ログイン',
    loginId: 'ログインID',
    memberRegisterBody: 'Member アカウントを申請すると、root または admin の承認後に利用できます。',
    memberRegisterSuccess: 'Member 登録申請を送信しました。承認後にログインできます。',
    memberRole: '希望権限',
    memberRoleAdmin: 'Admin',
    memberRoleStudent: 'Student',
    memberRoleTeacher: 'Teacher',
    memberRoleInvalid: '有効な権限を選択してください。',
    noAccount: 'まだ作成されたアカウントがありません。先に登録を完了してください。',
    password: 'パスワード',
    passwordSetupFailed: 'パスワードを準備できませんでした。しばらくしてからもう一度お試しください。',
    profile: 'プロフィール',
    profileAcademy: '所属学園',
    profileBody: '現在サインインしているアカウント情報です。',
    profileId: 'サインイン中ID',
    profileRole: '権限',
    protectedControls: '保護コントロール',
    protectedLocked: 'サインインするまでロックされています。',
    protectedSignin: '保護設定にサインイン',
    protectedUnlocked: '現在のアカウントで保護設定を利用できます。',
    registerRoot: 'Root 登録',
    registerRootBody: 'ライセンス、学園情報、root アカウント情報をまとめて登録します。',
    registerType: '登録タイプ',
    registerTypeUser: 'Member',
    registerTypeRoot: 'Root',
    register: '登録',
    registerBody: '登録タイプを選んで必要な情報を入力します。',
    registerCta: '登録情報を入力',
    registerHint: 'Root 登録が完了すると、そのままプロフィールに移動します。',
    registerSuccess: 'Root アカウントを作成しました。',
    registrationBusy: '現在登録を完了できません。しばらくしてからもう一度お試しください。',
    result: '結果',
    rootLoginId: 'root ログインID',
    rootAlreadyExists: 'この学園にはすでに root アカウントがあります。',
    settings: '設定',
    signIn: 'サインイン',
    signOut: 'サインアウト',
    theme: 'テーマ',
    unlocked: 'サインイン済みのため保護設定を利用できます。',
    licenseCode: 'ライセンスコード',
    licenseAssigned: 'このライセンスはすでに別の学園で使用されています。',
    licenseExpired: 'このライセンスは期限切れです。',
    licenseNotFound: 'ライセンスコードが見つかりません。',
    licenseUnavailable: 'このライセンスは現在登録に使用できません。',
    licenseRenewUnavailable: 'ライセンスは有効期限前のみ延長できます。',
    userRegisterPending: '申請後は root または admin が承認するまでログインできません。',
    requiredField: 'すべての項目を入力してください。',
    passwordMismatch: 'パスワードが一致しません。',
    signInFailed: '現在サインインできません。しばらくしてからもう一度お試しください。',
  },
  en: {
    academyCode: 'Academy Code',
    academyName: 'Academy Name',
    account: 'Account',
    allChecks: 'Run All Health Checks',
    allChecksHint: 'Run local, Docker, and cloud checks in sequence.',
    cloud: 'Cloud Server',
    devHealth: 'Developer Options',
    devHealthBody:
      'Check connectivity to each server from the desktop client.',
    devLicenseCreate: 'Create License',
    devLicenseCreateHint: 'Create one unassigned license.',
    devResult: 'Developer Action Result',
    devTableInit: 'Initialize Tables',
    devTableInitHint:
      'Recreate the managed tables and apply migrations in order.',
    dark: 'Dark',
    docker: 'Docker Server',
    env: 'Env',
    general: 'General',
    confirmPassword: 'Confirm Password',
    createAccount: 'Create Account',
    copyLicenseCode: 'Copy License Code',
    displayName: 'Display Name',
    guestHint:
      'Sign in with the account you created to view your profile and protected controls.',
    invalid: 'The account ID or password is incorrect.',
    accountInactive: 'This account is inactive.',
    accountOnHold: 'This account is currently on hold.',
    accountPending: 'This account is pending approval.',
    academyInactive: 'The academy for this account is inactive.',
    academyCreateFailed: 'We could not create the academy right now. Please try again.',
    duplicateLoginId: 'That login ID is already in use. Please choose another one.',
    language: 'Language',
    lastChecked: 'Last checked',
    light: 'Light',
    local: 'Local Server',
    locked: 'Protected settings are currently locked.',
    loginNotice: 'Login Notice',
    login: 'Login',
    loginId: 'Login ID',
    memberRegisterBody:
      'Submit a member account request and sign in after a root or admin approves it.',
    memberRegisterSuccess:
      'Your member registration request has been submitted. You can sign in after approval.',
    memberRole: 'Requested Role',
    memberRoleAdmin: 'Admin',
    memberRoleStudent: 'Student',
    memberRoleTeacher: 'Teacher',
    memberRoleInvalid: 'Please choose a valid role.',
    noAccount: 'No account has been created yet. Complete registration first.',
    password: 'Password',
    passwordSetupFailed:
      'We could not prepare your password right now. Please try again.',
    profile: 'Profile',
    profileAcademy: 'Academy',
    profileBody: 'This is the account currently signed in.',
    profileId: 'Signed-in ID',
    profileRole: 'Role',
    protectedControls: 'Protected controls',
    protectedLocked: 'Locked until you sign in.',
    protectedSignin: 'Sign in to protected settings',
    protectedUnlocked: 'Protected settings are available for the current account.',
    registerRoot: 'Root Register',
    registerRootBody:
      'Register the license, academy details, and root account in one flow.',
    registerType: 'Register Type',
    registerTypeUser: 'Member',
    registerTypeRoot: 'Root',
    register: 'Register',
    registerBody: 'Choose a register type and enter the required information.',
    registerCta: 'Enter registration details',
    registerHint: 'After root registration, you will move directly to the profile section.',
    registerSuccess: 'Your root account has been created.',
    registrationBusy: 'We could not complete registration right now. Please try again.',
    result: 'Result',
    rootLoginId: 'Root Login ID',
    rootAlreadyExists: 'This academy already has a root account.',
    settings: 'Settings',
    signIn: 'Sign in',
    signOut: 'Sign out',
    theme: 'Theme',
    unlocked: 'Protected settings are available because you are signed in.',
    licenseCode: 'License Code',
    licenseAssigned: 'This license has already been assigned to another academy.',
    licenseExpired: 'This license has expired.',
    licenseNotFound: 'That license code could not be found.',
    licenseUnavailable: 'This license is not available for registration.',
    licenseRenewUnavailable: 'This license can only be renewed before it expires.',
    userRegisterPending: 'After submission, you cannot sign in until a root or admin approves the account.',
    requiredField: 'Fill in all fields.',
    passwordMismatch: 'Passwords do not match.',
    signInFailed: 'We could not sign you in right now. Please try again.',
  },
} as const;

export function getDesktopShellLabels(language: LanguageMode) {
  return DESKTOP_SHELL_LABELS[language];
}
