import type {LanguageMode} from '../../../shared/shell-model';

export const DESKTOP_SHELL_LABELS = {
  ja: {
    academyCode: '学園コード',
    academyName: '学園名',
    account: 'アカウント',
    allChecks: '全ヘルスチェック実行',
    allChecksHint: 'ローカル、Docker、クラウドの順で確認します。',
    cloud: 'クラウドサーバー',
    devHealth: '開発者オプション',
    devHealthBody:
      '現在のデスクトップクライアントから各サーバー接続を確認します。',
    devLicenseCreate: 'ライセンス生成',
    devLicenseCreateHint: '未割り当てライセンスを 1 件発行します。',
    devResult: '開発者アクション結果',
    devTableInit: 'テーブル初期化',
    devTableInitHint: '管理対象テーブルを再作成し、マイグレーションを順に適用します。',
    dark: 'ダーク',
    docker: 'Dockerサーバー',
    env: '環境',
    general: '一般設定',
    confirmPassword: 'パスワード確認',
    createAccount: 'アカウント作成',
    copyLicenseCode: 'ライセンスコードをコピー',
    displayName: '表示名',
    guestHint: '登録したアカウントでログインするとプロフィールと保護コントロールを確認できます。',
    invalid: 'アカウントIDまたはパスワードが正しくありません。',
    language: '言語',
    lastChecked: '最終確認',
    light: 'ライト',
    local: 'ローカルサーバー',
    locked: '保護設定は現在ロックされています。',
    login: 'ログイン',
    loginId: 'ログインID',
    noAccount: 'まだ作成されたアカウントがありません。先に登録を完了してください。',
    password: 'パスワード',
    profile: 'プロフィール',
    profileAcademy: '所属学園',
    profileBody: '現在サインインしているアカウント情報です。',
    profileId: 'サインイン中ID',
    profileRole: '権限',
    protectedControls: '保護コントロール',
    protectedLocked: 'サインインするまでロックされています。',
    protectedSignin: '保護設定にサインイン',
    protectedUnlocked: '現在のアカウントで保護設定を利用できます。',
    registerRoot: 'Root 登録',
    registerRootBody: 'ライセンス、学園情報、root アカウント情報をまとめて登録します。',
    registerType: '登録タイプ',
    registerTypeUser: 'User',
    registerTypeRoot: 'Root',
    register: '登録',
    registerBody: '登録タイプを選んで必要な情報を入力します。',
    registerCta: '登録情報を入力',
    registerHint: 'Root 登録が完了すると、そのままプロフィールに移動します。',
    registerSuccess: 'Root アカウントを作成しました。',
    result: '結果',
    rootLoginId: 'root ログインID',
    settings: '設定',
    signIn: 'サインイン',
    signOut: 'サインアウト',
    theme: 'テーマ',
    unlocked: 'サインイン済みのため保護設定を利用できます。',
    licenseCode: 'ライセンスコード',
    userRegisterPending: 'User 登録フローは次のバッチで実装します。',
    requiredField: 'すべての項目を入力してください。',
    passwordMismatch: 'パスワードが一致しません。',
  },
  en: {
    academyCode: 'Academy Code',
    academyName: 'Academy Name',
    account: 'Account',
    allChecks: 'Run All Health Checks',
    allChecksHint: 'Run local, Docker, and cloud checks in sequence.',
    cloud: 'Cloud Server',
    devHealth: 'Developer Options',
    devHealthBody:
      'Check connectivity to each server from the desktop client.',
    devLicenseCreate: 'Create License',
    devLicenseCreateHint: 'Create one unassigned license.',
    devResult: 'Developer Action Result',
    devTableInit: 'Initialize Tables',
    devTableInitHint:
      'Recreate the managed tables and apply migrations in order.',
    dark: 'Dark',
    docker: 'Docker Server',
    env: 'Env',
    general: 'General',
    confirmPassword: 'Confirm Password',
    createAccount: 'Create Account',
    copyLicenseCode: 'Copy License Code',
    displayName: 'Display Name',
    guestHint:
      'Sign in with the account you created to view your profile and protected controls.',
    invalid: 'The account ID or password is incorrect.',
    language: 'Language',
    lastChecked: 'Last checked',
    light: 'Light',
    local: 'Local Server',
    locked: 'Protected settings are currently locked.',
    login: 'Login',
    loginId: 'Login ID',
    noAccount: 'No account has been created yet. Complete registration first.',
    password: 'Password',
    profile: 'Profile',
    profileAcademy: 'Academy',
    profileBody: 'This is the account currently signed in.',
    profileId: 'Signed-in ID',
    profileRole: 'Role',
    protectedControls: 'Protected controls',
    protectedLocked: 'Locked until you sign in.',
    protectedSignin: 'Sign in to protected settings',
    protectedUnlocked: 'Protected settings are available for the current account.',
    registerRoot: 'Root Register',
    registerRootBody:
      'Register the license, academy details, and root account in one flow.',
    registerType: 'Register Type',
    registerTypeUser: 'User',
    registerTypeRoot: 'Root',
    register: 'Register',
    registerBody: 'Choose a register type and enter the required information.',
    registerCta: 'Enter registration details',
    registerHint: 'After root registration, you will move directly to the profile section.',
    registerSuccess: 'Your root account has been created.',
    result: 'Result',
    rootLoginId: 'Root Login ID',
    settings: 'Settings',
    signIn: 'Sign in',
    signOut: 'Sign out',
    theme: 'Theme',
    unlocked: 'Protected settings are available because you are signed in.',
    licenseCode: 'License Code',
    userRegisterPending: 'The user register flow will be added in the next batch.',
    requiredField: 'Fill in all fields.',
    passwordMismatch: 'Passwords do not match.',
  },
} as const;

export function getDesktopShellLabels(language: LanguageMode) {
  return DESKTOP_SHELL_LABELS[language];
}
