import {StyleSheet} from 'react-native';

export const desktopShellStyles = StyleSheet.create({
  safeArea: {flex: 1},
  shell: {flex: 1, flexDirection: 'row'},
  sidebar: {width: 220, paddingTop: 24, paddingHorizontal: 16},
  sidebarItem: {
    borderRadius: 18,
    height: 56,
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  sidebarItemSpaced: {marginTop: 12},
  sidebarSubmenu: {gap: 8, marginTop: 10, marginLeft: 10},
  sidebarSubmenuAnimated: {overflow: 'hidden'},
  sidebarSubItem: {borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12},
  sidebarSubItemLabel: {fontSize: 14, fontWeight: '700'},
  sidebarSubItemLabelActive: {fontSize: 15},
  sidebarSubItemLabelInactive: {fontSize: 14},
  sidebarItemLabel: {fontSize: 18, fontWeight: '800'},
  sidebarItemLabelActive: {fontSize: 23},
  sidebarItemLabelInactive: {fontSize: 16},
  mainPanel: {flex: 1},
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderBottomWidth: 1,
  },
  menuButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuButtonLabel: {fontSize: 18, fontWeight: '800'},
  topBarTitle: {fontSize: 24, fontWeight: '800'},
  contentRow: {flex: 1, flexDirection: 'row'},
  body: {flex: 1, padding: 18},
  stack: {gap: 16, paddingBottom: 12},
  card: {padding: 20, borderRadius: 22, borderWidth: 1},
  cardTitle: {fontSize: 22, fontWeight: '800', marginBottom: 8},
  bodyText: {fontSize: 14, lineHeight: 22},
  bodyStrong: {fontSize: 14, fontWeight: '700', lineHeight: 22},
  fieldLabel: {fontSize: 13, fontWeight: '700', marginTop: 14, marginBottom: 8},
  optionRow: {flexDirection: 'row', gap: 10},
  optionChip: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 999,
    borderWidth: 1,
  },
  optionChipText: {fontSize: 14, fontWeight: '800'},
  input: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
  },
  errorText: {color: '#bc4749', fontSize: 13, fontWeight: '700', marginTop: 12},
  actionButton: {paddingHorizontal: 16, paddingVertical: 12, borderRadius: 16},
  actionText: {fontSize: 14, fontWeight: '800'},
  primaryCardAction: {padding: 18, borderRadius: 22},
  primaryCardActionTitle: {fontSize: 18, fontWeight: '800', marginBottom: 6},
  primaryCardActionHint: {fontSize: 13, lineHeight: 18},
  checkboxRow: {flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 16},
  checkboxBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxMark: {fontSize: 14, fontWeight: '800'},
  checkboxTextWrap: {flex: 1},
  checkboxTitle: {fontSize: 14, fontWeight: '800'},
  checkboxHint: {fontSize: 12, lineHeight: 18, marginTop: 2},
  resultPanel: {marginTop: 12, padding: 16, borderRadius: 18},
  resultLabel: {fontSize: 12, fontWeight: '800', letterSpacing: 1, marginBottom: 8},
  metaText: {fontSize: 12, lineHeight: 18, marginTop: 8},
});
